module.exports = {
	list : [{"Title":"Harry Potter and the Half-Blood Prince","metascore":"78"},
{"Title":"Tangled","metascore":"71"},
{"Title":"John Carter","metascore":"51"},
{"Title":"Superman Returns","metascore":"72"},
{"Title":"Pirates of the Caribbean: Dead Man's Chest","metascore":"53"},
{"Title":"Man of Steel","metascore":"55"},
{"Title":"Spider-Man 3","metascore":"59"},
{"Title":"Avatar","metascore":"83"},
{"Title":"The Hobbit: The Desolation of Smaug","metascore":"66"},
{"Title":"The Lone Ranger","metascore":"37"},
{"Title":"Jurassic World","metascore":"59"},
{"Title":"Pirates of the Caribbean: On Stranger Tides","metascore":"45"},
{"Title":"Transformers: Revenge of the Fallen","metascore":"35"},
{"Title":"Transformers: Age of Extinction","metascore":"32"},
{"Title":"Men in Black 3","metascore":"58"},
{"Title":"Pirates of the Caribbean: At World's End","metascore":"50"},
{"Title":"Robin Hood","metascore":"53"},
{"Title":"Quantum of Solace","metascore":"58"},
{"Title":"Snow White and the Huntsman","metascore":"57"},
{"Title":"Wreck-It Ralph","metascore":"72"},
{"Title":"Brave","metascore":"69"},
{"Title":"Van Helsing","metascore":"35"},
{"Title":"Shrek Forever After","metascore":"58"},
{"Title":"Alice in Wonderland","metascore":"53"},
{"Title":"Mission: Impossible III","metascore":"66"},
{"Title":"Kung Fu Panda 2","metascore":"67"},
{"Title":"Angels & Demons","metascore":"48"},
{"Title":"Indiana Jones and the Kingdom of the Crystal Skull","metascore":"65"},
{"Title":"Guardians of the Galaxy","metascore":"76"},
{"Title":"TRON: Legacy","metascore":"49"},
{"Title":"Maleficent","metascore":"56"},
{"Title":"Iron Man 3","metascore":"62"},
{"Title":"Frozen","metascore":"74"},
{"Title":"Jupiter Ascending","metascore":"40"},
{"Title":"Independence Day 2","metascore":"N/A"},
{"Title":"Valerian and the City of a Thousand Planets","metascore":"N/A"},
{"Title":"Disney's A Christmas Carol","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Transformers: Dark of the Moon","metascore":"42"},
{"Title":"The Making of 'Terminator: Genisys'","metascore":"N/A"},
{"Title":"Thor","metascore":"57"},
{"Title":"X-Men Origins: Wolverine","metascore":"40"},
{"Title":"The Matrix Revolutions","metascore":"47"},
{"Title":"The Dark Knight","metascore":"82"},
{"Title":"Alexander","metascore":"39"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Polar Express","metascore":"61"},
{"Title":"How to Train Your Dragon","metascore":"74"},
{"Title":"The Mummy: Tomb of the Dragon Emperor","metascore":"31"},
{"Title":"The Great Gatsby","metascore":"55"},
{"Title":"Poseidon","metascore":"50"},
{"Title":"G.I. Joe: The Rise of Cobra","metascore":"32"},
{"Title":"Big Hero 6","metascore":"74"},
{"Title":"Terminator 3: Rise of the Machines","metascore":"66"},
{"Title":"Star Trek Into Darkness","metascore":"72"},
{"Title":"A Christmas Carol","metascore":"55"},
{"Title":"Furious 7 High Octane","metascore":"N/A"},
{"Title":"I Am Legend","metascore":"65"},
{"Title":"Charlie and the Chocolate Factory","metascore":"72"},
{"Title":"Harry Potter and the Goblet of Fire","metascore":"81"},
{"Title":"Transformers","metascore":"61"},
{"Title":"World War Z","metascore":"63"},
{"Title":"Pearl Harbor","metascore":"44"},
{"Title":"Harry Potter and the Order of the Phoenix","metascore":"71"},
{"Title":"Captain America: The Winter Soldier","metascore":"70"},
{"Title":"The Matrix Reloaded","metascore":"62"},
{"Title":"X-Men: First Class","metascore":"65"},
{"Title":"Batman Begins","metascore":"70"},
{"Title":"Evan Almighty","metascore":"37"},
{"Title":"The Chronicles of Narnia: The Voyage of the Dawn Treader","metascore":"53"},
{"Title":"Night at the Museum: Battle of the Smithsonian","metascore":"42"},
{"Title":"Mad Max: Fury Road","metascore":"89"},
{"Title":"The Sorcerer's Apprentice","metascore":"46"},
{"Title":"The Curious Case of Benjamin Button","metascore":"70"},
{"Title":"Mission: Impossible - Ghost Protocol","metascore":"73"},
{"Title":"Stealth","metascore":"35"},
{"Title":"Lethal Weapon 4","metascore":"37"},
{"Title":"Thor: The Dark World","metascore":"54"},
{"Title":"Ratatouille","metascore":"96"},
{"Title":"X-Men: The Last Stand","metascore":"58"},
{"Title":"Fast and Furious 6: The Game","metascore":"N/A"},
{"Title":"Interstellar","metascore":"74"},
{"Title":"The Hobbit: An Unexpected Journey","metascore":"58"},
{"Title":"Spider-Man","metascore":"73"},
{"Title":"Hancock","metascore":"49"},
{"Title":"Tomorrowland","metascore":"60"},
{"Title":"The Amazing Spider-Man","metascore":"66"},
{"Title":"Wild Wild West","metascore":"38"},
{"Title":"The Avengers","metascore":"69"},
{"Title":"Cars 2","metascore":"57"},
{"Title":"Titanic","metascore":"N/A"},
{"Title":"Jack the Giant Slayer","metascore":"51"},
{"Title":"Terminator Salvation","metascore":"52"},
{"Title":"Dawn of the Planet of the Apes","metascore":"79"},
{"Title":"The Chronicles of Narnia: Prince Caspian","metascore":"62"},
{"Title":"47 Ronin","metascore":"28"},
{"Title":"Iron Man 2","metascore":"57"},
{"Title":"Oz the Great and Powerful","metascore":"44"},
{"Title":"2012","metascore":"49"},
{"Title":"Monsters University","metascore":"N/A"},
{"Title":"Green Lantern","metascore":"39"},
{"Title":"Up","metascore":"88"},
{"Title":"Inception","metascore":"74"},
{"Title":"Iron Man","metascore":"79"},
{"Title":"The Golden Compass","metascore":"51"},
{"Title":"Rush Hour 3","metascore":"44"},
{"Title":"Monsters vs. Aliens","metascore":"56"},
{"Title":"The Hobbit: The Battle of the Five Armies","metascore":"59"},
{"Title":"Battleship","metascore":"41"},
{"Title":"Edge of Tomorrow","metascore":"71"},
{"Title":"The Amazing Spider-Man 2","metascore":"53"},
{"Title":"King Kong","metascore":"N/A"},
{"Title":"Skyfall","metascore":"81"},
{"Title":"Toy Story 3","metascore":"92"},
{"Title":"Waterworld","metascore":"56"},
{"Title":"Singularity","metascore":"N/A"},
{"Title":"Spider-Man 2","metascore":"N/A"},
{"Title":"The Dark Knight Rises","metascore":"78"},
{"Title":"Pacific Rim","metascore":"64"},
{"Title":"Godzilla","metascore":"62"},
{"Title":"Shrek the Third","metascore":"58"},
{"Title":"The Chronicles of Narnia: The Lion, the Witch and the Wardrobe","metascore":"75"},
{"Title":"Hugo","metascore":"83"},
{"Title":"X-Men: Days of Future Past","metascore":"74"},
{"Title":"WALL·E","metascore":"94"},
{"Title":"Watchmen","metascore":"56"},
{"Title":"Fun with Dick and Jane","metascore":"47"},
{"Title":"Captain America: The First Avenger","metascore":"66"},
{"Title":"Armageddon","metascore":"42"},
{"Title":"Star Trek","metascore":"83"},
{"Title":"The Day After Tomorrow","metascore":"47"},
{"Title":"Sherlock Holmes: A Game of Shadows","metascore":"48"},
{"Title":"Die Another Day","metascore":"56"},
{"Title":"Rise of the Guardians","metascore":"57"},
{"Title":"Tarzan","metascore":"79"},
{"Title":"Sahara","metascore":"41"},
{"Title":"Mr. Peabody & Sherman","metascore":"59"},
{"Title":"How to Train Your Dragon 2","metascore":"76"},
{"Title":"The Incredible Hulk","metascore":"61"},
{"Title":"Teenage Mutant Ninja Turtles","metascore":"31"},
{"Title":"F/X2","metascore":"48"},
{"Title":"The Da Vinci Code","metascore":"46"},
{"Title":"Pirates of the Caribbean: The Curse of the Black Pearl","metascore":"63"},
{"Title":"Fast Five","metascore":"67"},
{"Title":"Harry Potter and the Sorcerer's Stone","metascore":"64"},
{"Title":"The Hunger Games: Mockingjay - Part 1","metascore":"64"},
{"Title":"Madagascar 3: Europe's Most Wanted","metascore":"60"},
{"Title":"Passengers","metascore":"40"},
{"Title":"Flushed Away","metascore":"N/A"},
{"Title":"Harry Potter and the Deathly Hallows: Part I","metascore":"N/A"},
{"Title":"Dinosaur","metascore":"56"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Wolfman","metascore":"43"},
{"Title":"Mars Needs Moms","metascore":"49"},
{"Title":"Mission: Impossible - Rogue Nation","metascore":"N/A"},
{"Title":"Dark Shadows","metascore":"55"},
{"Title":"Beowulf","metascore":"59"},
{"Title":"White House Down","metascore":"52"},
{"Title":"Wrath of the Titans","metascore":"37"},
{"Title":"Harry Potter and the Deathly Hallows: Part II","metascore":"N/A"},
{"Title":"Bolt","metascore":"67"},
{"Title":"G-Force","metascore":"41"},
{"Title":"R.I.P.D.","metascore":"25"},
{"Title":"Australia","metascore":"53"},
{"Title":"Night at the Museum: Secret of the Tomb","metascore":"47"},
{"Title":"After Earth","metascore":"33"},
{"Title":"Bee Movie","metascore":"54"},
{"Title":"The Twilight Saga: Breaking Dawn - Part 1","metascore":"45"},
{"Title":"The Last Airbender","metascore":"20"},
{"Title":"The Adventures of Tintin","metascore":"68"},
{"Title":"Troy","metascore":"56"},
{"Title":"Salt","metascore":"65"},
{"Title":"Rio 2","metascore":"49"},
{"Title":"Ant-Man","metascore":"N/A"},
{"Title":"Bad Boys II","metascore":"38"},
{"Title":"Puss in Boots","metascore":"65"},
{"Title":"Megamind","metascore":"63"},
{"Title":"Noah","metascore":"68"},
{"Title":"Madagascar: Escape 2 Africa","metascore":"N/A"},
{"Title":"The Bourne Ultimatum","metascore":"85"},
{"Title":"Kung Fu Panda","metascore":"73"},
{"Title":"Harry Potter and the Prisoner of Azkaban","metascore":"82"},
{"Title":"Home","metascore":"55"},
{"Title":"The Hunger Games: Catching Fire","metascore":"75"},
{"Title":"Penguins of Madagascar","metascore":"53"},
{"Title":"War of the Worlds","metascore":"73"},
{"Title":"Miami Vice","metascore":"65"},
{"Title":"Happy Feet Two","metascore":"N/A"},
{"Title":"Turbo","metascore":"58"},
{"Title":"The Croods","metascore":"55"},
{"Title":"Master and Commander: The Far Side of the World","metascore":"81"},
{"Title":"The Twilight Saga: Breaking Dawn - Part 2","metascore":"52"},
{"Title":"Final Fantasy: The Spirits Within","metascore":"49"},
{"Title":"The World Is Not Enough","metascore":"59"},
{"Title":"Rango","metascore":"75"},
{"Title":"Hulk","metascore":"N/A"},
{"Title":"The Last Samurai","metascore":"55"},
{"Title":"Exodus: Gods and Kings","metascore":"52"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"G.I. Joe: Retaliation","metascore":"41"},
{"Title":"Stuart Little 2","metascore":"66"},
{"Title":"RoboCop","metascore":"67"},
{"Title":"The Chronicles of Riddick","metascore":"38"},
{"Title":"How Do You Know?","metascore":"N/A"},
{"Title":"Trolls","metascore":"N/A"},
{"Title":"Life of Pi","metascore":"79"},
{"Title":"Charlie's Angels: Full Throttle","metascore":"48"},
{"Title":"Knight and Day","metascore":"46"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Ghost Rider","metascore":"35"},
{"Title":"Oblivion","metascore":"54"},
{"Title":"Godzilla","metascore":"62"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Island","metascore":"50"},
{"Title":"How the Grinch Stole Christmas","metascore":"46"},
{"Title":"Prometheus","metascore":"65"},
{"Title":"Batman","metascore":"66"},
{"Title":"The Bourne Legacy","metascore":"61"},
{"Title":"Total Recall","metascore":"57"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Windtalkers","metascore":"51"},
{"Title":"Dante's Peak","metascore":"43"},
{"Title":"Gulliver's Travels","metascore":"33"},
{"Title":"Gravity","metascore":"96"},
{"Title":"Gladiator","metascore":"64"},
{"Title":"R.F.D. 10,000 B.C.","metascore":"N/A"},
{"Title":"Public Enemies","metascore":"70"},
{"Title":"Speed Racer","metascore":"37"},
{"Title":"Insurgent","metascore":"42"},
{"Title":"Ender's Game","metascore":"51"},
{"Title":"Cloud Atlas","metascore":"55"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Tomorrow Never Dies","metascore":"56"},
{"Title":"The Lord of the Rings: The Fellowship of the Ring","metascore":"92"},
{"Title":"San Andreas","metascore":"43"},
{"Title":"Mr. and Mrs. Smith","metascore":"N/A"},
{"Title":"The Smurfs","metascore":"30"},
{"Title":"The Green Hornet","metascore":"39"},
{"Title":"Night at the Museum","metascore":"48"},
{"Title":"The Smurfs 2","metascore":"34"},
{"Title":"300: Rise of an Empire","metascore":"48"},
{"Title":"Real Steel","metascore":"56"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Cat in the Hat","metascore":"N/A"},
{"Title":"Clash of the Titans","metascore":"39"},
{"Title":"The Hunger Games: Mockingjay - Part 2","metascore":"N/A"},
{"Title":"Kingdom of Heaven","metascore":"63"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Ocean's Twelve","metascore":"58"},
{"Title":"The Patriot","metascore":"63"},
{"Title":"Monsters, Inc.","metascore":"78"},
{"Title":"Live Free or Die Hard","metascore":"69"},
{"Title":"The Wolverine","metascore":"60"},
{"Title":"Home on the Range","metascore":"50"},
{"Title":"Fantastic Four: Rise of the Silver Surfer","metascore":"N/A"},
{"Title":"Minority Report","metascore":"80"},
{"Title":"Lemony Snicket's A Series of Unfortunate Events","metascore":"62"},
{"Title":"The 13th Warrior","metascore":"42"},
{"Title":"True Lies","metascore":"63"},
{"Title":"Eragon","metascore":"38"},
{"Title":"National Treasure","metascore":"39"},
{"Title":"The Other Guys","metascore":"64"},
{"Title":"The Emperor's New Groove","metascore":"70"},
{"Title":"Hercules","metascore":"N/A"},
{"Title":"American Gangster","metascore":"76"},
{"Title":"Epic","metascore":"52"},
{"Title":"Eraser","metascore":"N/A"},
{"Title":"I, Robot","metascore":"59"},
{"Title":"Stuart Little","metascore":"N/A"},
{"Title":"Casino Royale","metascore":"81"},
{"Title":"The Aviator","metascore":"77"},
{"Title":"Terminator 2: Judgment Day","metascore":"68"},
{"Title":"Harry Potter and the Chamber of Secrets","metascore":"63"},
{"Title":"Little Fockers","metascore":"27"},
{"Title":"Django Unchained","metascore":"81"},
{"Title":"Ali","metascore":"65"},
{"Title":"The Wolf of Wall Street","metascore":"75"},
{"Title":"Where the Wild Things Are","metascore":"N/A"},
{"Title":"Around the World in 80 Days","metascore":"49"},
{"Title":"The Hunchback of Notre Dame","metascore":"N/A"},
{"Title":"Planet of the Apes","metascore":"50"},
{"Title":"The Town That Dreaded Sundown","metascore":"47"},
{"Title":"Gone in 60 Seconds","metascore":"N/A"},
{"Title":"Black Hawk Down","metascore":"74"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Batman Forever","metascore":"51"},
{"Title":"The Perfect Storm","metascore":"59"},
{"Title":"The A-Team","metascore":"47"},
{"Title":"The Princess and the Frog","metascore":"N/A"},
{"Title":"The Spiderwick Chronicles","metascore":"62"},
{"Title":"Elysium","metascore":"61"},
{"Title":"Green Zone","metascore":"63"},
{"Title":"Unstoppable","metascore":"69"},
{"Title":"Sex and the City 2","metascore":"27"},
{"Title":"A Good Day to Die Hard","metascore":"28"},
{"Title":"The Tourist","metascore":"37"},
{"Title":"Starship Troopers","metascore":"51"},
{"Title":"The Adventures of Pluto Nash","metascore":"12"},
{"Title":"Cloudy with a Chance of Meatballs","metascore":"66"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Blood Diamond","metascore":"64"},
{"Title":"The Lord of the Rings: The Two Towers","metascore":"88"},
{"Title":"Gangs of New York","metascore":"72"},
{"Title":"The Incredibles","metascore":"90"},
{"Title":"Peter Pan","metascore":"N/A"},
{"Title":"Percy Jackson & the Olympians: The Lightning Thief","metascore":"47"},
{"Title":"Sherlock Holmes","metascore":"57"},
{"Title":"Rush Hour 2","metascore":"48"},
{"Title":"Rio","metascore":"63"},
{"Title":"King Arthur","metascore":"46"},
{"Title":"The Lovely Bones","metascore":"42"},
{"Title":"Seventh Son","metascore":"30"},
{"Title":"Contact","metascore":"62"},
{"Title":"Lara Croft: Tomb Raider","metascore":"N/A"},
{"Title":"Cutthroat Island","metascore":"N/A"},
{"Title":"The Fifth Element","metascore":"N/A"},
{"Title":"End of Days","metascore":"33"},
{"Title":"The Road to El Dorado","metascore":"51"},
{"Title":"The Expendables 2","metascore":"51"},
{"Title":"The Alamo","metascore":"47"},
{"Title":"Ice Age: Dawn of the Dinosaurs","metascore":"50"},
{"Title":"Mission to Mars","metascore":"34"},
{"Title":"You Don't Mess with the Zohan","metascore":"54"},
{"Title":"Ice Age: Continental Drift","metascore":"49"},
{"Title":"Son of the Mask","metascore":"20"},
{"Title":"Land of the Lost","metascore":"32"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Stepford Wives","metascore":"42"},
{"Title":"Tropic Thunder","metascore":"71"},
{"Title":"Transcendence","metascore":"42"},
{"Title":"Catwoman","metascore":"27"},
{"Title":"Jurassic Park III","metascore":"42"},
{"Title":"The Mummy Returns","metascore":"48"},
{"Title":"The Spanish Prisoner","metascore":"70"},
{"Title":"Charlie's Angels","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Surf's Up","metascore":"64"},
{"Title":"The Lord of the Rings: The Return of the King","metascore":"94"},
{"Title":"Rise of the Planet of the Apes","metascore":"68"},
{"Title":"The Saint","metascore":"50"},
{"Title":"The Departed","metascore":"86"},
{"Title":"The Nutcracker in 3D","metascore":"18"},
{"Title":"Atlantis: The Lost Empire","metascore":"52"},
{"Title":"Cinderella","metascore":"N/A"},
{"Title":"Treasure Planet","metascore":"60"},
{"Title":"The Secret Life of Walter Mitty","metascore":"54"},
{"Title":"Volcano","metascore":"55"},
{"Title":"Fantastic Four","metascore":"40"},
{"Title":"Percy Jackson: Sea of Monsters","metascore":"39"},
{"Title":"Valkyrie","metascore":"56"},
{"Title":"The Expendables 3","metascore":"35"},
{"Title":"Die Hard: With a Vengeance","metascore":"58"},
{"Title":"What Lies Beneath","metascore":"51"},
{"Title":"Men in Black","metascore":"71"},
{"Title":"Twister","metascore":"N/A"},
{"Title":"Mulan","metascore":"71"},
{"Title":"The Devil's Own","metascore":"53"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Finding Nemo","metascore":"90"},
{"Title":"The Girl with the Dragon Tattoo","metascore":"71"},
{"Title":"Lara Croft Tomb Raider: The Cradle of Life","metascore":"43"},
{"Title":"Hollow Man","metascore":"N/A"},
{"Title":"The Haunted Mansion","metascore":"34"},
{"Title":"Spy Game","metascore":"63"},
{"Title":"Divergent","metascore":"48"},
{"Title":"Hotel Transylvania","metascore":"47"},
{"Title":"Cinderella Man","metascore":"69"},
{"Title":"Happy Feet","metascore":"N/A"},
{"Title":"Enemy of the State","metascore":"67"},
{"Title":"It's Complicated","metascore":"57"},
{"Title":"Cast Away","metascore":"73"},
{"Title":"Enchanted","metascore":"75"},
{"Title":"Toy Story 2","metascore":"88"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Seabiscuit","metascore":"72"},
{"Title":"The Bourne Supremacy","metascore":"73"},
{"Title":"Bicentennial Man","metascore":"42"},
{"Title":"Ocean's Thirteen","metascore":"62"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Horton Hears a Who!","metascore":"N/A"},
{"Title":"Air Force One","metascore":"61"},
{"Title":"Hannibal","metascore":"57"},
{"Title":"Ocean's Eleven","metascore":"74"},
{"Title":"Pixels","metascore":"N/A"},
{"Title":"Safe House","metascore":"52"},
{"Title":"The Interpreter","metascore":"62"},
{"Title":"K-19: The Widowmaker","metascore":"58"},
{"Title":"Fast & Furious 6","metascore":"61"},
{"Title":"102 Dalmatians","metascore":"35"},
{"Title":"Open Season","metascore":"49"},
{"Title":"Arthur Christmas","metascore":"69"},
{"Title":"The Rundown","metascore":"59"},
{"Title":"Last Action Hero","metascore":"44"},
{"Title":"Enemy at the Gates","metascore":"53"},
{"Title":"Memoirs of a Geisha","metascore":"N/A"},
{"Title":"The Fast and the Furious: Tokyo Drift","metascore":"46"},
{"Title":"The Holiday","metascore":"52"},
{"Title":"Mirror Mirror","metascore":"46"},
{"Title":"Tower Heist","metascore":"59"},
{"Title":"Cats","metascore":"N/A"},
{"Title":"Judge Dredd","metascore":"N/A"},
{"Title":"Meet Joe Black","metascore":"43"},
{"Title":"Zodiac","metascore":"78"},
{"Title":"Click","metascore":"45"},
{"Title":"Nutty Professor II: The Klumps","metascore":"38"},
{"Title":"Collateral Damage","metascore":"33"},
{"Title":"The Longest Yard","metascore":"48"},
{"Title":"Father's Day","metascore":"N/A"},
{"Title":"The Expendables","metascore":"45"},
{"Title":"Charlotte's Web","metascore":"68"},
{"Title":"Bruce Almighty","metascore":"46"},
{"Title":"Scott Pilgrim vs. the World","metascore":"69"},
{"Title":"Scooby-Doo","metascore":"35"},
{"Title":"Hellboy II: The Golden Army","metascore":"78"},
{"Title":"Batman Returns","metascore":"N/A"},
{"Title":"The Core","metascore":"48"},
{"Title":"The Hunger Games","metascore":"67"},
{"Title":"The 6th Day","metascore":"49"},
{"Title":"The Mummy","metascore":"48"},
{"Title":"Showtime","metascore":"32"},
{"Title":"Deep Impact","metascore":"40"},
{"Title":"Lilo & Stitch","metascore":"73"},
{"Title":"The Hangover Part II","metascore":"44"},
{"Title":"Get Smart","metascore":"54"},
{"Title":"Jumper","metascore":"35"},
{"Title":"Daredevil","metascore":"42"},
{"Title":"RED 2","metascore":"47"},
{"Title":"The Legend of Zorro","metascore":"47"},
{"Title":"Mighty Joe Young","metascore":"N/A"},
{"Title":"Eagle Eye","metascore":"43"},
{"Title":"Over the Hedge","metascore":"67"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Haunting","metascore":"N/A"},
{"Title":"Conspiracy Theory","metascore":"49"},
{"Title":"Flubber","metascore":"37"},
{"Title":"Shutter Island","metascore":"63"},
{"Title":"The Day the Earth Stood Still","metascore":"40"},
{"Title":"The Pink Panther","metascore":"38"},
{"Title":"Four Christmases","metascore":"41"},
{"Title":"Mission: Impossible","metascore":"60"},
{"Title":"Grown Ups 2","metascore":"19"},
{"Title":"Just Go with It","metascore":"33"},
{"Title":"Fury","metascore":"64"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Something's Gotta Give","metascore":"66"},
{"Title":"Bedtime Stories","metascore":"33"},
{"Title":"The Lion King","metascore":"83"},
{"Title":"Cloudy with a Chance of Meatballs 2","metascore":"59"},
{"Title":"The Wild","metascore":"47"},
{"Title":"Nine","metascore":"49"},
{"Title":"Cars","metascore":"73"},
{"Title":"A Sound of Thunder","metascore":"24"},
{"Title":"What Dreams May Come","metascore":"44"},
{"Title":"The Invasion","metascore":"45"},
{"Title":"The League of Extraordinary Gentlemen","metascore":"30"},
{"Title":"Journey 2: The Mysterious Island","metascore":"41"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Shark Tale","metascore":"48"},
{"Title":"Hidalgo","metascore":"54"},
{"Title":"The Simpsons Movie","metascore":"80"},
{"Title":"Spirit: Stallion of the Cimarron","metascore":"52"},
{"Title":"Mars Attacks!","metascore":"52"},
{"Title":"Shrek 2","metascore":"75"},
{"Title":"Timeline","metascore":"28"},
{"Title":"The Brothers Grimm","metascore":"51"},
{"Title":"Hercules","metascore":"N/A"},
{"Title":"Pompeii","metascore":"39"},
{"Title":"Daylight","metascore":"N/A"},
{"Title":"Face/Off","metascore":"82"},
{"Title":"Space Jam","metascore":"N/A"},
{"Title":"Bewitched","metascore":"34"},
{"Title":"Cold Mountain","metascore":"73"},
{"Title":"Robots","metascore":"64"},
{"Title":"The Book of Eli","metascore":"53"},
{"Title":"Oceans","metascore":"75"},
{"Title":"Zookeeper","metascore":"30"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Con Air","metascore":"52"},
{"Title":"Babe: Pig in the City","metascore":"N/A"},
{"Title":"Alvin and the Chipmunks: Chipwrecked","metascore":"24"},
{"Title":"Six Days Seven Nights","metascore":"51"},
{"Title":"Swordfish","metascore":"32"},
{"Title":"Jack and Jill","metascore":"23"},
{"Title":"Surrogates","metascore":"45"},
{"Title":"The Time Machine","metascore":"42"},
{"Title":"Red Dragon","metascore":"N/A"},
{"Title":"The Postman","metascore":"29"},
{"Title":"Lost in Space","metascore":"42"},
{"Title":"Little Nicky","metascore":"38"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Manchurian Candidate","metascore":"76"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Thirteen Days","metascore":"67"},
{"Title":"Red Planet","metascore":"34"},
{"Title":"Soldier","metascore":"N/A"},
{"Title":"X-Men","metascore":"64"},
{"Title":"Charlie Wilson's War","metascore":"69"},
{"Title":"Minions","metascore":"N/A"},
{"Title":"Despicable Me 2","metascore":"62"},
{"Title":"Jarhead","metascore":"58"},
{"Title":"Flight of the Phoenix","metascore":"47"},
{"Title":"Independence Day","metascore":"59"},
{"Title":"The Terminal","metascore":"55"},
{"Title":"Anna and the King","metascore":"56"},
{"Title":"Walking with Dinosaurs","metascore":"N/A"},
{"Title":"Talladega Nights: The Ballad of Ricky Bobby","metascore":"66"},
{"Title":"Spanglish","metascore":"48"},
{"Title":"Hairspray","metascore":"81"},
{"Title":"First Knight","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Vertical Limit","metascore":"48"},
{"Title":"Evolution","metascore":"40"},
{"Title":"Unbreakable","metascore":"62"},
{"Title":"Lady in the Water","metascore":"36"},
{"Title":"Driven","metascore":"N/A"},
{"Title":"The Majestic","metascore":"27"},
{"Title":"Looney Tunes: Back in Action","metascore":"64"},
{"Title":"Immortals","metascore":"46"},
{"Title":"Munich","metascore":"74"},
{"Title":"Wanted","metascore":"64"},
{"Title":"Inspector Gadget","metascore":"N/A"},
{"Title":"Killers","metascore":"21"},
{"Title":"The Kingdom","metascore":"56"},
{"Title":"The SpongeBob Movie: Sponge Out of Water","metascore":"62"},
{"Title":"Constantine","metascore":"50"},
{"Title":"The Adventures of Rocky & Bullwinkle","metascore":"N/A"},
{"Title":"Sucker Punch","metascore":"33"},
{"Title":"50 First Dates","metascore":"48"},
{"Title":"Virus","metascore":"19"},
{"Title":"A Beautiful Mind","metascore":"72"},
{"Title":"Madagascar","metascore":"57"},
{"Title":"Hostage","metascore":"44"},
{"Title":"Ice Age: The Meltdown","metascore":"58"},
{"Title":"Alvin and the Chipmunks: The Squeakquel","metascore":"41"},
{"Title":"Monster House","metascore":"68"},
{"Title":"Grown Ups","metascore":"30"},
{"Title":"Sphere","metascore":"35"},
{"Title":"Hollywood Homicide","metascore":"47"},
{"Title":"Children of Men","metascore":"84"},
{"Title":"The Lost World: Jurassic Park","metascore":"59"},
{"Title":"The Village","metascore":"44"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Stardust","metascore":"66"},
{"Title":"Runaway Bride","metascore":"N/A"},
{"Title":"Rock of Ages","metascore":"47"},
{"Title":"Killer Elite","metascore":"44"},
{"Title":"S.W.A.T.","metascore":"45"},
{"Title":"Seven Years in Tibet","metascore":"N/A"},
{"Title":"Two Brothers","metascore":"63"},
{"Title":"Die Hard 2","metascore":"67"},
{"Title":"Star Trek: Insurrection","metascore":"64"},
{"Title":"Who Framed Roger Rabbit","metascore":"83"},
{"Title":"Battle: Los Angeles","metascore":"N/A"},
{"Title":"Fool's Gold","metascore":"29"},
{"Title":"Ransom","metascore":"60"},
{"Title":"2 Fast 2 Furious","metascore":"38"},
{"Title":"The Siege","metascore":"N/A"},
{"Title":"Die Hard 2","metascore":"67"},
{"Title":"Inglourious Basterds","metascore":"69"},
{"Title":"S.W.A.T.","metascore":"45"},
{"Title":"Sleepy Hollow","metascore":"65"},
{"Title":"Hook","metascore":"52"},
{"Title":"Alvin and the Chipmunks: The Squeakquel","metascore":"41"},
{"Title":"Vanilla Sky","metascore":"N/A"},
{"Title":"Battle: Los Angeles","metascore":"N/A"},
{"Title":"Runaway Bride","metascore":"N/A"},
{"Title":"Ransom","metascore":"60"},
{"Title":"Olympus Has Fallen","metascore":"41"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Who Framed Roger Rabbit","metascore":"83"},
{"Title":"War Horse","metascore":"72"},
{"Title":"xXx","metascore":"48"},
{"Title":"The Monuments Men","metascore":"52"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Wolf","metascore":"N/A"},
{"Title":"Big Fish","metascore":"58"},
{"Title":"The Abyss","metascore":"62"},
{"Title":"The Dilemma","metascore":"46"},
{"Title":"Hercules","metascore":"N/A"},
{"Title":"Star Trek: Insurrection","metascore":"64"},
{"Title":"Cars","metascore":"73"},
{"Title":"The Siege","metascore":"N/A"},
{"Title":"Dracula Untold","metascore":"40"},
{"Title":"We Were Soldiers","metascore":"65"},
{"Title":"Rock of Ages","metascore":"47"},
{"Title":"Stardust","metascore":"66"},
{"Title":"Sky Captain and the World of Tomorrow","metascore":"64"},
{"Title":"Hart's War","metascore":"49"},
{"Title":"Escape Plan","metascore":"49"},
{"Title":"Seven Years in Tibet","metascore":"N/A"},
{"Title":"Underworld: Awakening","metascore":"39"},
{"Title":"I Spy","metascore":"35"},
{"Title":"Bad Company","metascore":"37"},
{"Title":"Hard Rain","metascore":"N/A"},
{"Title":"Rollerball","metascore":"14"},
{"Title":"Killer Elite","metascore":"44"},
{"Title":"Doom","metascore":"34"},
{"Title":"Basic Instinct 2","metascore":"26"},
{"Title":"Blackhat","metascore":"51"},
{"Title":"The Twilight Saga: Eclipse","metascore":"58"},
{"Title":"Mystery Men","metascore":"65"},
{"Title":"The Score","metascore":"71"},
{"Title":"Dreamcatcher","metascore":"35"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Body of Lies","metascore":"57"},
{"Title":"Abraham Lincoln: Vampire Hunter","metascore":"42"},
{"Title":"Hall Pass","metascore":"45"},
{"Title":"The Insider","metascore":"84"},
{"Title":"Money Train","metascore":"N/A"},
{"Title":"The Last Legion","metascore":"37"},
{"Title":"Entrapment","metascore":"54"},
{"Title":"Last Man Standing","metascore":"N/A"},
{"Title":"The Making of 'The X Files: Fight the Future'","metascore":"N/A"},
{"Title":"Ice Age","metascore":"60"},
{"Title":"Apollo 13","metascore":"77"},
{"Title":"You've Got Mail","metascore":"57"},
{"Title":"What Women Want","metascore":"47"},
{"Title":"Need for Speed","metascore":"39"},
{"Title":"The Santa Clause 2","metascore":"48"},
{"Title":"The General's Daughter","metascore":"47"},
{"Title":"The Prince of Egypt","metascore":"64"},
{"Title":"Collateral","metascore":"71"},
{"Title":"Cats","metascore":"N/A"},
{"Title":"Two Weeks Notice","metascore":"42"},
{"Title":"RED","metascore":"60"},
{"Title":"Starsky & Hutch","metascore":"55"},
{"Title":"The Scorpion King","metascore":"45"},
{"Title":"Eat Pray Love","metascore":"50"},
{"Title":"Daddy Day Care","metascore":"39"},
{"Title":"Antz","metascore":"72"},
{"Title":"Coraline","metascore":"80"},
{"Title":"Cheaper by the Dozen 2","metascore":"34"},
{"Title":"Jingle All the Way","metascore":"N/A"},
{"Title":"The Happening","metascore":"34"},
{"Title":"All Access: Making Michael Jackson's This Is It","metascore":"N/A"},
{"Title":"A Civil Action","metascore":"68"},
{"Title":"Any Given Sunday","metascore":"52"},
{"Title":"The Family Man","metascore":"42"},
{"Title":"The Jackal","metascore":"36"},
{"Title":"ParaNorman","metascore":"72"},
{"Title":"Paycheck","metascore":"43"},
{"Title":"Rules of Engagement","metascore":"45"},
{"Title":"The Boxtrolls","metascore":"61"},
{"Title":"The Tale of Despereaux","metascore":"53"},
{"Title":"Star Trek: Nemesis","metascore":"51"},
{"Title":"Miss Congeniality 2: Armed and Fabulous","metascore":"34"},
{"Title":"Jack Ryan: Shadow Recruit","metascore":"57"},
{"Title":"Year One","metascore":"34"},
{"Title":"Shooter","metascore":"53"},
{"Title":"The Tuxedo","metascore":"30"},
{"Title":"Man on Fire","metascore":"47"},
{"Title":"The Horse Whisperer","metascore":"65"},
{"Title":"Contagion","metascore":"70"},
{"Title":"Jack Reacher","metascore":"50"},
{"Title":"Days of Thunder","metascore":"60"},
{"Title":"The Shaggy Dog","metascore":"N/A"},
{"Title":"Deep Blue Sea","metascore":"54"},
{"Title":"Hellboy","metascore":"72"},
{"Title":"Up Close","metascore":"N/A"},
{"Title":"Kangaroo Jack","metascore":"16"},
{"Title":"Righteous Kill","metascore":"36"},
{"Title":"Under Siege 2: Dark Territory","metascore":"N/A"},
{"Title":"Ladder 49","metascore":"47"},
{"Title":"Invictus","metascore":"74"},
{"Title":"Duplicity","metascore":"69"},
{"Title":"Alien: Resurrection","metascore":"63"},
{"Title":"Mercury Rising","metascore":"N/A"},
{"Title":"Intolerable Cruelty","metascore":"71"},
{"Title":"The Relic","metascore":"N/A"},
{"Title":"The Soloist","metascore":"61"},
{"Title":"Practical Magic","metascore":"46"},
{"Title":"Dragonfly","metascore":"25"},
{"Title":"My Favorite Martian","metascore":"N/A"},
{"Title":"Edtv","metascore":"48"},
{"Title":"Reign of Fire","metascore":"39"},
{"Title":"Planet 51","metascore":"39"},
{"Title":"Flyboys","metascore":"47"},
{"Title":"Meet Dave","metascore":"43"},
{"Title":"Event Horizon","metascore":"35"},
{"Title":"The Avengers","metascore":"69"},
{"Title":"Winter's Tale","metascore":"31"},
{"Title":"The Legend of Bagger Vance","metascore":"47"},
{"Title":"Almost Famous","metascore":"90"},
{"Title":"In the Name of the King: A Dungeon Siege Tale","metascore":"15"},
{"Title":"Dark Water","metascore":"52"},
{"Title":"Holy Man","metascore":"41"},
{"Title":"Edge of Darkness","metascore":"55"},
{"Title":"Inkheart","metascore":"N/A"},
{"Title":"The Great Raid","metascore":"48"},
{"Title":"Gangster Squad","metascore":"40"},
{"Title":"State of Play","metascore":"64"},
{"Title":"Analyze That","metascore":"37"},
{"Title":"Supernova","metascore":"19"},
{"Title":"The Last Castle","metascore":"43"},
{"Title":"xXx: State of the Union","metascore":"37"},
{"Title":"Priest","metascore":"41"},
{"Title":"Sinbad: Legend of the Seven Seas","metascore":"48"},
{"Title":"The Black Dahlia","metascore":"49"},
{"Title":"The Mortal Instruments: City of Bones","metascore":"N/A"},
{"Title":"The Spirit","metascore":"30"},
{"Title":"The Sentinel","metascore":"49"},
{"Title":"Trouble with the Curve","metascore":"58"},
{"Title":"Beyond Borders","metascore":"N/A"},
{"Title":"Rambo III","metascore":"36"},
{"Title":"Red Tails","metascore":"46"},
{"Title":"The Internship","metascore":"42"},
{"Title":"Just Like Heaven","metascore":"47"},
{"Title":"Sabrina","metascore":"72"},
{"Title":"DragonHeart","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"That's My Boy","metascore":"31"},
{"Title":"Devil's Advocate","metascore":"N/A"},
{"Title":"Did You Hear About the Morgans?","metascore":"27"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Leatherheads","metascore":"56"},
{"Title":"Sex and the City","metascore":"53"},
{"Title":"After the Sunset","metascore":"38"},
{"Title":"The Flintstones in Viva Rock Vegas","metascore":"27"},
{"Title":"American Sniper","metascore":"72"},
{"Title":"Ghost Rider: Spirit of Vengeance","metascore":"32"},
{"Title":"The Pacifier","metascore":"30"},
{"Title":"The Pursuit of Happyness","metascore":"64"},
{"Title":"Alvin and the Chipmunks","metascore":"39"},
{"Title":"Superman","metascore":"86"},
{"Title":"Captain Corelli's Mandolin","metascore":"36"},
{"Title":"Pocahontas","metascore":"58"},
{"Title":"Meet the Parents","metascore":"73"},
{"Title":"Anger Management","metascore":"52"},
{"Title":"Captain Phillips","metascore":"83"},
{"Title":"George of the Jungle","metascore":"53"},
{"Title":"Paddington","metascore":"77"},
{"Title":"The Equalizer","metascore":"57"},
{"Title":"Maid in Manhattan","metascore":"N/A"},
{"Title":"The Nutty Professor","metascore":"62"},
{"Title":"Stargate","metascore":"N/A"},
{"Title":"R.V. 2014","metascore":"N/A"},
{"Title":"Date Night","metascore":"56"},
{"Title":"City of Angels","metascore":"54"},
{"Title":"Bowfinger","metascore":"71"},
{"Title":"Executive Decision","metascore":"N/A"},
{"Title":"Muppets Most Wanted","metascore":"61"},
{"Title":"Casino","metascore":"73"},
{"Title":"Turbulence","metascore":"N/A"},
{"Title":"You, Me and Dupree","metascore":"46"},
{"Title":"Lolita","metascore":"N/A"},
{"Title":"Elizabethtown","metascore":"45"},
{"Title":"The Godfather: Part III","metascore":"60"},
{"Title":"All the King's Men","metascore":"37"},
{"Title":"Bulletproof Monk","metascore":"40"},
{"Title":"The Break-Up","metascore":"N/A"},
{"Title":"Lucky You","metascore":"49"},
{"Title":"A Very Long Engagement","metascore":"N/A"},
{"Title":"Creating a World: Aeon Flux","metascore":"N/A"},
{"Title":"The Adjustment Bureau","metascore":"60"},
{"Title":"Mamma Mia!","metascore":"51"},
{"Title":"Moneyball","metascore":"87"},
{"Title":"Thunderbirds","metascore":"36"},
{"Title":"Queen's Blade 2: The Evil Eye","metascore":"N/A"},
{"Title":"Captain Phillips","metascore":"83"},
{"Title":"Pocahontas","metascore":"58"},
{"Title":"How to Lose a Guy in 10 Days","metascore":"45"},
{"Title":"The Pursuit of Happyness","metascore":"64"},
{"Title":"Anger Management","metascore":"52"},
{"Title":"Elizabeth: The Golden Age","metascore":"45"},
{"Title":"Turbulence","metascore":"N/A"},
{"Title":"The Fan","metascore":"32"},
{"Title":"Super 8","metascore":"72"},
{"Title":"Domino","metascore":"36"},
{"Title":"Zero Dark Thirty","metascore":"95"},
{"Title":"Chain Reaction","metascore":"N/A"},
{"Title":"Imagine That","metascore":"54"},
{"Title":"Grindhouse","metascore":"77"},
{"Title":"Creating a World: Aeon Flux","metascore":"N/A"},
{"Title":"Me, Myself & Irene","metascore":"49"},
{"Title":"Law Abiding Citizen","metascore":"34"},
{"Title":"Deck the Halls","metascore":"28"},
{"Title":"Moulin Rouge","metascore":"N/A"},
{"Title":"Elizabethtown","metascore":"45"},
{"Title":"All the King's Men","metascore":"37"},
{"Title":"Gigli","metascore":"18"},
{"Title":"Domestic Disturbance","metascore":"29"},
{"Title":"Into the Blue","metascore":"45"},
{"Title":"Thunderbirds","metascore":"36"},
{"Title":"The Messenger: The Story of Joan of Arc","metascore":"54"},
{"Title":"Lolita","metascore":"N/A"},
{"Title":"The Adjustment Bureau","metascore":"60"},
{"Title":"Fair Game","metascore":"69"},
{"Title":"Eye See You","metascore":"N/A"},
{"Title":"Bulletproof Monk","metascore":"40"},
{"Title":"You, Me and Dupree","metascore":"46"},
{"Title":"Eastern Promises","metascore":"82"},
{"Title":"A Very Long Engagement","metascore":"N/A"},
{"Title":"The Godfather: Part III","metascore":"60"},
{"Title":"Seven Pounds","metascore":"36"},
{"Title":"Gamer","metascore":"27"},
{"Title":"Queen's Blade 2: The Evil Eye","metascore":"N/A"},
{"Title":"Dream House","metascore":"35"},
{"Title":"Superman II","metascore":"87"},
{"Title":"The Life of David Gale","metascore":"31"},
{"Title":"As Good as It Gets","metascore":"67"},
{"Title":"Bullet to the Head","metascore":"48"},
{"Title":"Man of the House","metascore":"35"},
{"Title":"The Life Aquatic with Steve Zissou","metascore":"62"},
{"Title":"The Iron Giant","metascore":"85"},
{"Title":"Your Highness","metascore":"31"},
{"Title":"Beautiful Creatures","metascore":"N/A"},
{"Title":"The Judge","metascore":"48"},
{"Title":"Syriana","metascore":"76"},
{"Title":"Into the Storm","metascore":"44"},
{"Title":"The Game","metascore":"N/A"},
{"Title":"Don't Say a Word","metascore":"38"},
{"Title":"Resident Evil: Apocalypse","metascore":"35"},
{"Title":"Hansel & Gretel: Witch Hunters","metascore":"21"},
{"Title":"The Book of Life","metascore":"67"},
{"Title":"Outbreak","metascore":"N/A"},
{"Title":"I Am Number Four","metascore":"36"},
{"Title":"Unfaithful","metascore":"63"},
{"Title":"Christmas with the Kranks","metascore":"22"},
{"Title":"The Forgotten","metascore":"43"},
{"Title":"Inside Man","metascore":"76"},
{"Title":"The Ring Two","metascore":"44"},
{"Title":"Failure to Launch","metascore":"N/A"},
{"Title":"We Bought a Zoo","metascore":"58"},
{"Title":"Crazy, Stupid, Love.","metascore":"68"},
{"Title":"V for Vendetta","metascore":"62"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Twilight Saga: New Moon","metascore":"44"},
{"Title":"Non-Stop","metascore":"56"},
{"Title":"Yes Man","metascore":"46"},
{"Title":"Mr. Deeds","metascore":"24"},
{"Title":"Man on the Moon","metascore":"58"},
{"Title":"The Change-Up","metascore":"39"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Knowing","metascore":"41"},
{"Title":"Stepmom","metascore":"58"},
{"Title":"The Thin Red Line","metascore":"78"},
{"Title":"From Paris with Love","metascore":"42"},
{"Title":"Patch Adams","metascore":"25"},
{"Title":"Ted","metascore":"62"},
{"Title":"Casino","metascore":"73"},
{"Title":"Catch Me If You Can","metascore":"76"},
{"Title":"Robin Hood: Prince of Thieves","metascore":"N/A"},
{"Title":"Valentine's Day","metascore":"34"},
{"Title":"Mamma Mia!","metascore":"51"},
{"Title":"Flags of Our Fathers","metascore":"79"},
{"Title":"Beloved","metascore":"57"},
{"Title":"Shaft","metascore":"50"},
{"Title":"The Break-Up","metascore":"N/A"},
{"Title":"Gods and Generals","metascore":"30"},
{"Title":"Escape from L.A.","metascore":"N/A"},
{"Title":"The International","metascore":"52"},
{"Title":"Run All Night","metascore":"59"},
{"Title":"Twisted","metascore":"26"},
{"Title":"Blood Work","metascore":"64"},
{"Title":"The Pirates! Band of Misfits","metascore":"N/A"},
{"Title":"Defiance","metascore":"58"},
{"Title":"Striptease","metascore":"N/A"},
{"Title":"Murder by Numbers","metascore":"50"},
{"Title":"Assassins","metascore":"N/A"},
{"Title":"Basic","metascore":"34"},
{"Title":"Hannibal Rising","metascore":"35"},
{"Title":"Hereafter","metascore":"56"},
{"Title":"The Host","metascore":"35"},
{"Title":"The Story of Us","metascore":"37"},
{"Title":"Semi-Pro","metascore":"47"},
{"Title":"Jack Frost","metascore":"N/A"},
{"Title":"On Deadly Ground","metascore":"N/A"},
{"Title":"Marmaduke","metascore":"30"},
{"Title":"Raising Helen","metascore":"38"},
{"Title":"For Love of the Game","metascore":"43"},
{"Title":"Ninja Assassin","metascore":"34"},
{"Title":"The Hunted","metascore":"40"},
{"Title":"The Watch","metascore":"36"},
{"Title":"Stuck on You","metascore":"62"},
{"Title":"Evita","metascore":"45"},
{"Title":"Burlesque","metascore":"47"},
{"Title":"Ronin","metascore":"67"},
{"Title":"Instinct","metascore":"43"},
{"Title":"Changeling","metascore":"63"},
{"Title":"Bridget Jones: The Edge of Reason","metascore":"44"},
{"Title":"The Replacements","metascore":"30"},
{"Title":"The Peacemaker","metascore":"43"},
{"Title":"Silent Hill","metascore":"30"},
{"Title":"Gremlins 2: The New Batch","metascore":"N/A"},
{"Title":"Beverly Hills Cop III","metascore":"N/A"},
{"Title":"Out of Time","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Beach","metascore":"N/A"},
{"Title":"Child 44","metascore":"N/A"},
{"Title":"Muppets Most Wanted","metascore":"61"},
{"Title":"Executive Decision","metascore":"N/A"},
{"Title":"The Forbidden Kingdom","metascore":"57"},
{"Title":"Free Birds","metascore":"38"},
{"Title":"Shanghai Noon","metascore":"77"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Jade","metascore":"N/A"},
{"Title":"G.I. Jane","metascore":"62"},
{"Title":"Baby's Day Out","metascore":"N/A"},
{"Title":"The Big Bounce","metascore":"N/A"},
{"Title":"Street Fighter: The Legend of Chun-Li","metascore":"17"},
{"Title":"Drive Angry","metascore":"44"},
{"Title":"Mad City","metascore":"45"},
{"Title":"What Planet Are You From?","metascore":"41"},
{"Title":"Death to Smoochy","metascore":"38"},
{"Title":"The Scarlet Letter","metascore":"N/A"},
{"Title":"Outlander","metascore":"N/A"},
{"Title":"Anna Karenina","metascore":"63"},
{"Title":"The Adventures of Ford Fairlane","metascore":"24"},
{"Title":"Traffic","metascore":"86"},
{"Title":"Hannibal the Conqueror","metascore":"N/A"},
{"Title":"Panic Room","metascore":"65"},
{"Title":"Taken 3","metascore":"26"},
{"Title":"The Ring","metascore":"57"},
{"Title":"Chappie","metascore":"41"},
{"Title":"Rat Race","metascore":"52"},
{"Title":"K-PAX","metascore":"49"},
{"Title":"3:10 to Yuma","metascore":"76"},
{"Title":"Story of Your Life","metascore":"N/A"},
{"Title":"The Thomas Crown Affair","metascore":"72"},
{"Title":"Indiana Jones and the Last Crusade","metascore":"65"},
{"Title":"The Tooth Fairy","metascore":"N/A"},
{"Title":"The Bone Collector","metascore":"45"},
{"Title":"The Cotton Club","metascore":"N/A"},
{"Title":"Rambo","metascore":"46"},
{"Title":"The One","metascore":"25"},
{"Title":"Out of Sight","metascore":"85"},
{"Title":"Happily N'Ever After","metascore":"28"},
{"Title":"The Cable Guy","metascore":"N/A"},
{"Title":"Bedazzled","metascore":"49"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Three Kings","metascore":"82"},
{"Title":"Riding in Cars with Boys","metascore":"43"},
{"Title":"Dick Tracy","metascore":"N/A"},
{"Title":"America's Sweethearts","metascore":"N/A"},
{"Title":"Mary Reilly","metascore":"44"},
{"Title":"Star Trek: First Contact","metascore":"71"},
{"Title":"Inchon","metascore":"N/A"},
{"Title":"Jonah Hex","metascore":"33"},
{"Title":"Prisoners","metascore":"74"},
{"Title":"Courage Under Fire","metascore":"77"},
{"Title":"Liar Liar","metascore":"68"},
{"Title":"Patriot Games","metascore":"N/A"},
{"Title":"The Bucket List","metascore":"42"},
{"Title":"The Flintstones","metascore":"38"},
{"Title":"A Bug's Life","metascore":"77"},
{"Title":"Insomnia","metascore":"78"},
{"Title":"The Muppets","metascore":"75"},
{"Title":"Scary Movie 3","metascore":"49"},
{"Title":"Taken 2","metascore":"45"},
{"Title":"Training Day","metascore":"70"},
{"Title":"Anaconda","metascore":"37"},
{"Title":"Galaxy Quest","metascore":"70"},
{"Title":"Coach Carter","metascore":"57"},
{"Title":"Jack","metascore":"31"},
{"Title":"Scary Movie 2","metascore":"29"},
{"Title":"Changing Lanes","metascore":"69"},
{"Title":"Journey to the Center of the Earth","metascore":"57"},
{"Title":"Yours, Mine and Ours","metascore":"N/A"},
{"Title":"Blade","metascore":"45"},
{"Title":"The Client","metascore":"65"},
{"Title":"The Hitchhiker's Guide to the Galaxy","metascore":"N/A"},
{"Title":"Love Actually","metascore":"55"},
{"Title":"Solaris","metascore":"65"},
{"Title":"Miss Congeniality","metascore":"43"},
{"Title":"The Bounty Hunter","metascore":"22"},
{"Title":"Monster-in-Law","metascore":"31"},
{"Title":"Resident Evil: Extinction","metascore":"41"},
{"Title":"Johnny English","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Multiplicity","metascore":"N/A"},
{"Title":"Kicking and Screaming","metascore":"75"},
{"Title":"The Specialist","metascore":"N/A"},
{"Title":"The Pelican Brief","metascore":"50"},
{"Title":"Blended","metascore":"31"},
{"Title":"Savages","metascore":"59"},
{"Title":"Babylon A.D.","metascore":"26"},
{"Title":"Tin Cup","metascore":"60"},
{"Title":"The River Wild","metascore":"N/A"},
{"Title":"Freedom","metascore":"N/A"},
{"Title":"Argo","metascore":"86"},
{"Title":"Big Trouble","metascore":"47"},
{"Title":"Charlie St. Cloud","metascore":"37"},
{"Title":"Rambo: First Blood Part II","metascore":"N/A"},
{"Title":"Miracle at St. Anna","metascore":"37"},
{"Title":"Pinocchio","metascore":"N/A"},
{"Title":"Sleepers","metascore":"49"},
{"Title":"The Juror","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Heaven's Gate","metascore":"N/A"},
{"Title":"Along Came Polly","metascore":"44"},
{"Title":"28 Days","metascore":"46"},
{"Title":"Love in the Time of Cholera","metascore":"43"},
{"Title":"The Heat","metascore":"60"},
{"Title":"Finding Forrester","metascore":"62"},
{"Title":"The Mechanic","metascore":"49"},
{"Title":"The Fugitive","metascore":"88"},
{"Title":"21 Jump Street","metascore":"69"},
{"Title":"Boomerang","metascore":"45"},
{"Title":"Shadow Conspiracy","metascore":"N/A"},
{"Title":"The Firm","metascore":"58"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Cleopatra","metascore":"N/A"},
{"Title":"The Sweetest Thing","metascore":"32"},
{"Title":"Lord of War","metascore":"62"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Chicken Run","metascore":"88"},
{"Title":"Hero","metascore":"84"},
{"Title":"McHale's Navy","metascore":"N/A"},
{"Title":"The Interview","metascore":"52"},
{"Title":"The Mirror Has Two Faces","metascore":"N/A"},
{"Title":"High Crimes","metascore":"48"},
{"Title":"Big Trouble","metascore":"47"},
{"Title":"Freedom","metascore":"N/A"},
{"Title":"The Fugitive","metascore":"88"},
{"Title":"Argo","metascore":"86"},
{"Title":"Rambo: First Blood Part II","metascore":"N/A"},
{"Title":"Sleepers","metascore":"49"},
{"Title":"The Interview","metascore":"52"},
{"Title":"Heaven's Gate","metascore":"N/A"},
{"Title":"Pinocchio","metascore":"N/A"},
{"Title":"The Heat","metascore":"60"},
{"Title":"The Mechanic","metascore":"49"},
{"Title":"28 Days","metascore":"46"},
{"Title":"Shadow Conspiracy","metascore":"N/A"},
{"Title":"Finding Forrester","metascore":"62"},
{"Title":"The Sweetest Thing","metascore":"32"},
{"Title":"Boomerang","metascore":"45"},
{"Title":"Love in the Time of Cholera","metascore":"43"},
{"Title":"Along Came Polly","metascore":"44"},
{"Title":"The Firm","metascore":"58"},
{"Title":"Charlie St. Cloud","metascore":"37"},
{"Title":"Miracle at St. Anna","metascore":"37"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Here Comes the Boom","metascore":"40"},
{"Title":"Super Mario Bros.","metascore":"N/A"},
{"Title":"The Big Year","metascore":"53"},
{"Title":"The Mirror Has Two Faces","metascore":"N/A"},
{"Title":"Secret Window","metascore":"46"},
{"Title":"The Odd Life of Timothy Green","metascore":"47"},
{"Title":"The Living Daylights","metascore":"N/A"},
{"Title":"Jersey Boys","metascore":"54"},
{"Title":"Legal Eagles","metascore":"N/A"},
{"Title":"The Nativity Story","metascore":"52"},
{"Title":"Bounce","metascore":"52"},
{"Title":"In Time","metascore":"53"},
{"Title":"Black Knight","metascore":"N/A"},
{"Title":"The Pianist","metascore":"85"},
{"Title":"From Hell","metascore":"54"},
{"Title":"Mirrors","metascore":"N/A"},
{"Title":"Hot Pursuit","metascore":"30"},
{"Title":"The Back-up Plan","metascore":"34"},
{"Title":"House of Wax","metascore":"41"},
{"Title":"Predator 2","metascore":"N/A"},
{"Title":"Flash Gordon","metascore":"63"},
{"Title":"Closer","metascore":"65"},
{"Title":"Superhero Movie","metascore":"33"},
{"Title":"Street Fighter","metascore":"N/A"},
{"Title":"Ella Enchanted","metascore":"53"},
{"Title":"Abduction","metascore":"25"},
{"Title":"Alex Cross","metascore":"30"},
{"Title":"Walk Hard: The Dewey Cox Story","metascore":"63"},
{"Title":"Midnight in the Garden of Good and Evil","metascore":"57"},
{"Title":"Jersey Girl","metascore":"43"},
{"Title":"Heist","metascore":"66"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Bait","metascore":"N/A"},
{"Title":"The Four Feathers","metascore":"49"},
{"Title":"The X Files: I Want to Believe","metascore":"47"},
{"Title":"Blast from the Past","metascore":"48"},
{"Title":"Wonder Boys","metascore":"N/A"},
{"Title":"American Outlaws","metascore":"25"},
{"Title":"Wimbledon","metascore":"59"},
{"Title":"A Good Year","metascore":"47"},
{"Title":"Whiteout","metascore":"N/A"},
{"Title":"Cursed","metascore":"31"},
{"Title":"Hoffa","metascore":"50"},
{"Title":"The Tree of Life","metascore":"85"},
{"Title":"Valiant","metascore":"45"},
{"Title":"Zoom","metascore":"26"},
{"Title":"Sabotage","metascore":"41"},
{"Title":"Flight of the Intruder","metascore":"N/A"},
{"Title":"Broken City","metascore":"49"},
{"Title":"Premium Rush","metascore":"66"},
{"Title":"The Young Victoria","metascore":"64"},
{"Title":"Furry Vengeance","metascore":"23"},
{"Title":"Lions for Lambs","metascore":"47"},
{"Title":"The Shipping News","metascore":"47"},
{"Title":"Parker","metascore":"42"},
{"Title":"Untraceable","metascore":"32"},
{"Title":"The Order","metascore":"21"},
{"Title":"Radio Flyer","metascore":"N/A"},
{"Title":"Femme Fatale","metascore":"59"},
{"Title":"The Making of 'Dungeons and Dragons'","metascore":"N/A"},
{"Title":"Punisher: War Zone","metascore":"30"},
{"Title":"Warriors of Virtue","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Logan's War: Bound by Honor","metascore":"N/A"},
{"Title":"Mandela: Long Walk to Freedom","metascore":"60"},
{"Title":"Lion of the Desert","metascore":"N/A"},
{"Title":"Biutiful","metascore":"58"},
{"Title":"Snakes on a Plane","metascore":"58"},
{"Title":"Safe","metascore":"55"},
{"Title":"The Watcher","metascore":"22"},
{"Title":"The Maze Runner","metascore":"56"},
{"Title":"The Darkest Hour","metascore":"16"},
{"Title":"Luther","metascore":"N/A"},
{"Title":"Reds","metascore":"N/A"},
{"Title":"I Dreamed of Africa","metascore":"33"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Playing for Keeps","metascore":"27"},
{"Title":"Black Mass","metascore":"N/A"},
{"Title":"The Punisher","metascore":"33"},
{"Title":"Thunder and the House of Magic","metascore":"47"},
{"Title":"Ride with the Devil","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Lovers","metascore":"N/A"},
{"Title":"Bandidas","metascore":"N/A"},
{"Title":"The Astronaut's Wife","metascore":"37"},
{"Title":"Bringing Out the Dead","metascore":"70"},
{"Title":"Get Shorty","metascore":"82"},
{"Title":"Meet the Spartans","metascore":"9"},
{"Title":"The Cabin in the Woods","metascore":"72"},
{"Title":"Secondhand Lions","metascore":"52"},
{"Title":"Step Up 3D","metascore":"45"},
{"Title":"Midnight Run","metascore":"78"},
{"Title":"Mortal Kombat: Annihilation","metascore":"11"},
{"Title":"Hanna","metascore":"65"},
{"Title":"Stranger Than Fiction","metascore":"67"},
{"Title":"Entourage","metascore":"N/A"},
{"Title":"Drag Me to Hell","metascore":"83"},
{"Title":"Carrie","metascore":"N/A"},
{"Title":"Blue Crush","metascore":"61"},
{"Title":"30 Days of Night","metascore":"N/A"},
{"Title":"Take the Lead","metascore":"55"},
{"Title":"The Age of Adaline","metascore":"51"},
{"Title":"Side Effects","metascore":"75"},
{"Title":"What's the Worst That Could Happen?","metascore":"37"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Little Shop of Horrors","metascore":"81"},
{"Title":"Original Sin","metascore":"33"},
{"Title":"The Fifth Estate","metascore":"49"},
{"Title":"Self/less","metascore":"N/A"},
{"Title":"The Raven","metascore":"44"},
{"Title":"Brothers","metascore":"58"},
{"Title":"Accidental Love","metascore":"20"},
{"Title":"The Face of an Angel","metascore":"37"},
{"Title":"Viy","metascore":"N/A"},
{"Title":"The Constant Gardener","metascore":"82"},
{"Title":"Rain Man","metascore":"65"},
{"Title":"Schindler's List","metascore":"93"},
{"Title":"The Help","metascore":"62"},
{"Title":"The Bodyguard","metascore":"N/A"},
{"Title":"The Passion of the Christ","metascore":"47"},
{"Title":"W.","metascore":"56"},
{"Title":"Welcome to Mooseport","metascore":"33"},
{"Title":"Mrs. Doubtfire","metascore":"53"},
{"Title":"The Curse of the Jade Scorpion","metascore":"52"},
{"Title":"Blood and Wine","metascore":"N/A"},
{"Title":"Taken","metascore":"50"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Agent Cody Banks 2: Destination London","metascore":"32"},
{"Title":"The Best of Me","metascore":"29"},
{"Title":"Freddy vs. Jason","metascore":"37"},
{"Title":"Ride Along","metascore":"41"},
{"Title":"Scooby-Doo 2: Monsters Unleashed","metascore":"34"},
{"Title":"Cloverfield","metascore":"64"},
{"Title":"Gran Torino","metascore":"72"},
{"Title":"Legally Blonde 2: Red, White & Blonde","metascore":"47"},
{"Title":"Flipper","metascore":"N/A"},
{"Title":"Money Talks","metascore":"N/A"},
{"Title":"Rugrats Go Wild","metascore":"38"},
{"Title":"The Grey","metascore":"64"},
{"Title":"The Sisterhood of the Traveling Pants","metascore":"N/A"},
{"Title":"Nothing to Lose","metascore":"N/A"},
{"Title":"Finding Neverland","metascore":"67"},
{"Title":"Hide and Seek","metascore":"N/A"},
{"Title":"Final Destination 3","metascore":"41"},
{"Title":"There Will Be Blood","metascore":"92"},
{"Title":"The Wild Thornberrys Movie","metascore":"69"},
{"Title":"Contraband","metascore":"51"},
{"Title":"Jimmy Neutron: Boy Genius","metascore":"N/A"},
{"Title":"Agent Cody Banks","metascore":"41"},
{"Title":"The Omen","metascore":"N/A"},
{"Title":"The Lucky One","metascore":"39"},
{"Title":"Parental Guidance","metascore":"N/A"},
{"Title":"Dear John","metascore":"43"},
{"Title":"Tyler Perry's A Madea Christmas","metascore":"28"},
{"Title":"No Country for Old Men","metascore":"91"},
{"Title":"Bridge to Terabithia","metascore":"74"},
{"Title":"Nanny McPhee","metascore":"59"},
{"Title":"The Counselor","metascore":"48"},
{"Title":"Half Past Dead","metascore":"23"},
{"Title":"Bright Lights, Big City","metascore":"N/A"},
{"Title":"The Ruins","metascore":"44"},
{"Title":"Fly Me to the Moon","metascore":"N/A"},
{"Title":"My Soul to Take","metascore":"25"},
{"Title":"The Girl Next Door","metascore":"47"},
{"Title":"Cirque du Soleil: Worlds Away","metascore":"51"},
{"Title":"Warrior","metascore":"71"},
{"Title":"Lifeforce","metascore":"N/A"},
{"Title":"The Adventures of Pinocchio","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Unaccompanied Minors","metascore":"43"},
{"Title":"The Next Best Thing","metascore":"25"},
{"Title":"Hot Rod","metascore":"N/A"},
{"Title":"Brokedown Palace","metascore":"44"},
{"Title":"The Box","metascore":"47"},
{"Title":"Mrs. Winterbourne","metascore":"35"},
{"Title":"Michael Collins","metascore":"60"},
{"Title":"Big Trouble in Little China","metascore":"N/A"},
{"Title":"Stealing Harvard","metascore":"25"},
{"Title":"Legend","metascore":"N/A"},
{"Title":"Abandon","metascore":"N/A"},
{"Title":"The Conspirator","metascore":"55"},
{"Title":"Sheena","metascore":"N/A"},
{"Title":"Straw Dogs","metascore":"N/A"},
{"Title":"Stop-Loss","metascore":"61"},
{"Title":"Stone Cold","metascore":"N/A"},
{"Title":"Gettysburg","metascore":"N/A"},
{"Title":"Possession","metascore":"52"},
{"Title":"The Powerpuff Girls","metascore":"N/A"},
{"Title":"Underclassman","metascore":"N/A"},
{"Title":"Deception","metascore":"31"},
{"Title":"Say It Isn't So","metascore":"21"},
{"Title":"The Greatest Game Ever Played","metascore":"55"},
{"Title":"BloodRayne","metascore":"18"},
{"Title":"Maximum Risk","metascore":"N/A"},
{"Title":"Angela's Ashes","metascore":"54"},
{"Title":"The Road","metascore":"64"},
{"Title":"King's Ransom","metascore":"11"},
{"Title":"Venom","metascore":"25"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Love Ranch","metascore":"37"},
{"Title":"Red Sky","metascore":"N/A"},
{"Title":"The World's Fastest Indian","metascore":"68"},
{"Title":"Bad Lieutenant: Port of Call New Orleans","metascore":"69"},
{"Title":"Me and Orson Welles","metascore":"73"},
{"Title":"Ironclad","metascore":"42"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Where the Truth Lies","metascore":"47"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Without Limits","metascore":"N/A"},
{"Title":"Tank Girl","metascore":"N/A"},
{"Title":"Blindness","metascore":"45"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Scream 2","metascore":"63"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Hoax","metascore":"70"},
{"Title":"Think Like a Man Too","metascore":"38"},
{"Title":"On the Road","metascore":"56"},
{"Title":"Return to Me","metascore":"54"},
{"Title":"Old School","metascore":"54"},
{"Title":"The Whole Nine Yards","metascore":"47"},
{"Title":"The Men Who Stare at Goats","metascore":"54"},
{"Title":"Rocky Balboa","metascore":"63"},
{"Title":"Star Trek IV: The Voyage Home","metascore":"67"},
{"Title":"Girl, Interrupted","metascore":"51"},
{"Title":"Zack and Miri Make a Porno","metascore":"56"},
{"Title":"Double Take","metascore":"25"},
{"Title":"The Adventurer: The Curse of the Midas Box","metascore":"39"},
{"Title":"Reagan","metascore":"N/A"},
{"Title":"Muppets from Space","metascore":"N/A"},
{"Title":"Dangerous Liaisons","metascore":"74"},
{"Title":"Waterloo","metascore":"N/A"},
{"Title":"Win a Date with Tad Hamilton!","metascore":"52"},
{"Title":"Footloose","metascore":"N/A"},
{"Title":"The Game Plan","metascore":"44"},
{"Title":"The Santa Clause","metascore":"57"},
{"Title":"The Bridges of Madison County","metascore":"66"},
{"Title":"Son of God","metascore":"37"},
{"Title":"The Animal","metascore":"43"},
{"Title":"Gandhi","metascore":"N/A"},
{"Title":"Diary of a Wimpy Kid: Dog Days","metascore":"54"},
{"Title":"The Net","metascore":"51"},
{"Title":"Underworld","metascore":"42"},
{"Title":"The Hundred-Foot Journey","metascore":"55"},
{"Title":"The Informant!","metascore":"66"},
{"Title":"I Am Sam","metascore":"28"},
{"Title":"Derailed","metascore":"40"},
{"Title":"Traitor","metascore":"60"},
{"Title":"Delivery Man","metascore":"44"},
{"Title":"Shadowlands","metascore":"N/A"},
{"Title":"Jay and Silent Bob Strike Back","metascore":"51"},
{"Title":"Deuce Bigalow: European Gigolo","metascore":"23"},
{"Title":"Mad Money","metascore":"41"},
{"Title":"The Greatest Story Ever Told","metascore":"N/A"},
{"Title":"Twilight","metascore":"56"},
{"Title":"A Guy Thing","metascore":"27"},
{"Title":"Loser","metascore":"35"},
{"Title":"Envy","metascore":"31"},
{"Title":"Ghost Town","metascore":"72"},
{"Title":"The Man Who Knew Too Little","metascore":"N/A"},
{"Title":"Be Kind Rewind","metascore":"52"},
{"Title":"Capitalism: A Love Story","metascore":"61"},
{"Title":"What's Your Number?","metascore":"35"},
{"Title":"One Night with the King","metascore":"38"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Disaster Movie","metascore":"15"},
{"Title":"The Weather Man","metascore":"61"},
{"Title":"Bullets Over Broadway","metascore":"N/A"},
{"Title":"Death Sentence","metascore":"36"},
{"Title":"Deconstructing Harry","metascore":"61"},
{"Title":"Let Me In","metascore":"79"},
{"Title":"Battle of the Year","metascore":"29"},
{"Title":"Everybody's Fine","metascore":"47"},
{"Title":"12 Rounds","metascore":"38"},
{"Title":"Undisputed","metascore":"58"},
{"Title":"Death at a Funeral","metascore":"67"},
{"Title":"We're No Angels","metascore":"N/A"},
{"Title":"Flash of Genius","metascore":"57"},
{"Title":"Three to Tango","metascore":"N/A"},
{"Title":"Lockout","metascore":"48"},
{"Title":"Willard","metascore":"61"},
{"Title":"A Dangerous Method","metascore":"76"},
{"Title":"The Quiet American","metascore":"84"},
{"Title":"Doogal","metascore":"N/A"},
{"Title":"Bandslam","metascore":"N/A"},
{"Title":"Chasing Mavericks","metascore":"45"},
{"Title":"The Brothers Bloom","metascore":"N/A"},
{"Title":"Connie","metascore":"N/A"},
{"Title":"A Most Violent Year","metascore":"79"},
{"Title":"Bon voyage","metascore":"68"},
{"Title":"Topsy Turvy","metascore":"N/A"},
{"Title":"Birth","metascore":"50"},
{"Title":"Machete Kills","metascore":"41"},
{"Title":"Strange Wilderness","metascore":"12"},
{"Title":"Proof","metascore":"N/A"},
{"Title":"The Man","metascore":"N/A"},
{"Title":"The Cold Light of Day","metascore":"22"},
{"Title":"Marci X","metascore":"20"},
{"Title":"Dylan Dog: Dead of Night","metascore":"31"},
{"Title":"People I Know","metascore":"53"},
{"Title":"Little Boy","metascore":"30"},
{"Title":"Equilibrium","metascore":"33"},
{"Title":"The Oogieloves in the Big Balloon Adventure","metascore":"32"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Code Name: The Cleaner","metascore":"33"},
{"Title":"Just Married","metascore":"28"},
{"Title":"A Scanner Darkly","metascore":"73"},
{"Title":"The Game of Their Lives","metascore":"47"},
{"Title":"3 Ninjas Kick Back","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"An American Carol","metascore":"20"},
{"Title":"I'm Not There","metascore":"N/A"},
{"Title":"Passchendaele","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Touch","metascore":"N/A"},
{"Title":"Alone in the Dark","metascore":"9"},
{"Title":"Everyone Says I Love You","metascore":"N/A"},
{"Title":"Ramanujan","metascore":"N/A"},
{"Title":"Sweet Charity","metascore":"N/A"},
{"Title":"The Painted Veil","metascore":"N/A"},
{"Title":"Hands of Stone","metascore":"N/A"},
{"Title":"The History of Love","metascore":"N/A"},
{"Title":"The Proposition","metascore":"N/A"},
{"Title":"The Yards","metascore":"58"},
{"Title":"A Cinderella Story","metascore":"25"},
{"Title":"I Can Do Bad All by Myself","metascore":"55"},
{"Title":"The Maid's Room","metascore":"39"},
{"Title":"The Children of Huang Shi","metascore":"49"},
{"Title":"Survivor","metascore":"N/A"},
{"Title":"Zambezia","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Synecdoche, New York","metascore":"67"},
{"Title":"Back to the Future","metascore":"86"},
{"Title":"The Shining","metascore":"61"},
{"Title":"Mutiny on the Bounty","metascore":"N/A"},
{"Title":"Gone Baby Gone","metascore":"72"},
{"Title":"The Book Thief","metascore":"53"},
{"Title":"Sex Drive","metascore":"49"},
{"Title":"Notorious","metascore":"N/A"},
{"Title":"Can't Stop the Music","metascore":"N/A"},
{"Title":"A Funny Thing Happened on the Way to the Forum","metascore":"N/A"},
{"Title":"The Frozen Ground","metascore":"N/A"},
{"Title":"Predator","metascore":"36"},
{"Title":"The Family Stone","metascore":"56"},
{"Title":"Firestorm","metascore":"N/A"},
{"Title":"Thomas and the Magic Railroad","metascore":"19"},
{"Title":"Bad Teacher","metascore":"47"},
{"Title":"Diary of a Wimpy Kid: Rodrick Rules","metascore":"51"},
{"Title":"Scary Movie","metascore":"48"},
{"Title":"The Devil's Double","metascore":"52"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Three Kingdoms: Resurrection of the Dragon","metascore":"N/A"},
{"Title":"The Nutcracker","metascore":"N/A"},
{"Title":"Legally Blonde","metascore":"59"},
{"Title":"Labor Day","metascore":"52"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Big","metascore":"72"},
{"Title":"Catch That Kid","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"127 Hours","metascore":"82"},
{"Title":"Orange County","metascore":"48"},
{"Title":"Life as a House","metascore":"45"},
{"Title":"The Switch","metascore":"52"},
{"Title":"The Fog","metascore":"N/A"},
{"Title":"Nine 1/2 Weeks","metascore":"50"},
{"Title":"Honey","metascore":"37"},
{"Title":"My All American","metascore":"N/A"},
{"Title":"The Amityville Horror","metascore":"33"},
{"Title":"The Tailor of Panama","metascore":"66"},
{"Title":"Love Happens","metascore":"33"},
{"Title":"Peggy Sue Got Married","metascore":"N/A"},
{"Title":"Steamboy","metascore":"66"},
{"Title":"Under the Tuscan Sun","metascore":"52"},
{"Title":"Birdman: Or (The Unexpected Virtue of Ignorance)","metascore":"88"},
{"Title":"Star Trek III: The Search for Spock","metascore":"55"},
{"Title":"All Good Things","metascore":"57"},
{"Title":"Fear and Loathing in Las Vegas","metascore":"41"},
{"Title":"Being Julia","metascore":"65"},
{"Title":"Austin Powers: International Man of Mystery","metascore":"51"},
{"Title":"Left Behind","metascore":"12"},
{"Title":"Mao's Last Dancer","metascore":"55"},
{"Title":"The Mask","metascore":"56"},
{"Title":"Metallica Through the Never","metascore":"61"},
{"Title":"Unforgettable","metascore":"N/A"},
{"Title":"Kansas City","metascore":"57"},
{"Title":"Neighbors","metascore":"68"},
{"Title":"Blow Out","metascore":"N/A"},
{"Title":"Dwegons and Leprechauns","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Catch-22","metascore":"N/A"},
{"Title":"Rapa Nui","metascore":"N/A"},
{"Title":"The Tempest","metascore":"N/A"},
{"Title":"The Legend of the Lone Ranger","metascore":"N/A"},
{"Title":"Jobs","metascore":"44"},
{"Title":"Spy Hard","metascore":"N/A"},
{"Title":"Dances with Wolves","metascore":"72"},
{"Title":"The Fall of the Roman Empire","metascore":"N/A"},
{"Title":"The Invention of Lying","metascore":"58"},
{"Title":"Adaptation","metascore":"N/A"},
{"Title":"CJ7","metascore":"46"},
{"Title":"Mean Girls","metascore":"66"},
{"Title":"Won't Back Down","metascore":"42"},
{"Title":"Prom Night","metascore":"17"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Exorcism of Emily Rose","metascore":"46"},
{"Title":"Gosford Park","metascore":"90"},
{"Title":"Amadeus","metascore":"93"},
{"Title":"Bad Santa","metascore":"70"},
{"Title":"Take Me Home Tonight","metascore":"42"},
{"Title":"Observe and Report","metascore":"54"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Barbershop 2: Back in Business","metascore":"59"},
{"Title":"Deuce Bigalow: Male Gigolo","metascore":"30"},
{"Title":"Blue Jasmine","metascore":"N/A"},
{"Title":"And So It Goes","metascore":"38"},
{"Title":"Small Time Crooks","metascore":"69"},
{"Title":"Getaway","metascore":"22"},
{"Title":"Glory","metascore":"N/A"},
{"Title":"Megaforce","metascore":"N/A"},
{"Title":"I Love You, Beth Cooper","metascore":"32"},
{"Title":"Ed Wood","metascore":"70"},
{"Title":"Center Stage","metascore":"52"},
{"Title":"Raging Bull","metascore":"92"},
{"Title":"The Ice Storm","metascore":"72"},
{"Title":"Youth in Revolt","metascore":"63"},
{"Title":"Fame","metascore":"N/A"},
{"Title":"RocknRolla","metascore":"53"},
{"Title":"Young Sherlock Holmes","metascore":"N/A"},
{"Title":"Conan the Destroyer","metascore":"N/A"},
{"Title":"Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan","metascore":"89"},
{"Title":"Dragonslayer","metascore":"N/A"},
{"Title":"Troop Beverly Hills","metascore":"N/A"},
{"Title":"Soul Surfer","metascore":"53"},
{"Title":"Hamlet","metascore":"N/A"},
{"Title":"United 93","metascore":"90"},
{"Title":"The Railway Man","metascore":"59"},
{"Title":"Anything Else","metascore":"N/A"},
{"Title":"Restoration","metascore":"N/A"},
{"Title":"The Crazies","metascore":"55"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"House on Haunted Hill","metascore":"28"},
{"Title":"Sea of Love","metascore":"N/A"},
{"Title":"Leap Year","metascore":"33"},
{"Title":"Phantom","metascore":"40"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Carlos","metascore":"94"},
{"Title":"The Salton Sea","metascore":"41"},
{"Title":"The Informers","metascore":"20"},
{"Title":"One Man's Hero","metascore":"24"},
{"Title":"I Come with the Rain","metascore":"N/A"},
{"Title":"Day of the Dead","metascore":"N/A"},
{"Title":"Renaissance","metascore":"57"},
{"Title":"The Last Station","metascore":"76"},
{"Title":"The Prince","metascore":"19"},
{"Title":"Red Sonja","metascore":"N/A"},
{"Title":"I Am Wrath","metascore":"N/A"},
{"Title":"Red Lights","metascore":"36"},
{"Title":"Hotel Rwanda","metascore":"79"},
{"Title":"Black Nativity","metascore":"48"},
{"Title":"Beerfest","metascore":"N/A"},
{"Title":"Madea Goes to Jail","metascore":"50"},
{"Title":"Superbad","metascore":"76"},
{"Title":"Wolves","metascore":"37"},
{"Title":"Aliens","metascore":"87"},
{"Title":"I Know What You Did Last Summer","metascore":"52"},
{"Title":"Step Up 2: The Streets","metascore":"50"},
{"Title":"Nowhere to Run","metascore":"N/A"},
{"Title":"The Marine","metascore":"45"},
{"Title":"The Hurt Locker","metascore":"94"},
{"Title":"Tuck Everlasting","metascore":"66"},
{"Title":"Country Strong","metascore":"45"},
{"Title":"Firestarter","metascore":"N/A"},
{"Title":"Freddy Got Fingered","metascore":"13"},
{"Title":"The Man with the Iron Fists","metascore":"51"},
{"Title":"U2 3D","metascore":"83"},
{"Title":"Disturbing Behavior","metascore":"N/A"},
{"Title":"Confidence","metascore":"59"},
{"Title":"Whip It","metascore":"68"},
{"Title":"A Most Wanted Man","metascore":"73"},
{"Title":"One Day","metascore":"48"},
{"Title":"The Pirates Who Don't Do Anything: A VeggieTales Movie","metascore":"49"},
{"Title":"Brazil","metascore":"88"},
{"Title":"New York Stories","metascore":"N/A"},
{"Title":"Barney's Great Adventure","metascore":"N/A"},
{"Title":"Eye of the Beholder","metascore":"29"},
{"Title":"Dark Blue","metascore":"57"},
{"Title":"Whatever It Takes","metascore":"20"},
{"Title":"Promised Land","metascore":"55"},
{"Title":"Knockaround Guys","metascore":"30"},
{"Title":"Peeples","metascore":"52"},
{"Title":"Post Grad","metascore":"35"},
{"Title":"In Bruges","metascore":"67"},
{"Title":"Killing Them Softly","metascore":"64"},
{"Title":"The Rocker","metascore":"53"},
{"Title":"Nowhere to Run","metascore":"N/A"},
{"Title":"The Marine","metascore":"45"},
{"Title":"Country Strong","metascore":"45"},
{"Title":"Tuck Everlasting","metascore":"66"},
{"Title":"Disturbing Behavior","metascore":"N/A"},
{"Title":"The Hurt Locker","metascore":"94"},
{"Title":"A Most Wanted Man","metascore":"73"},
{"Title":"Eye of the Beholder","metascore":"29"},
{"Title":"The Man with the Iron Fists","metascore":"51"},
{"Title":"The Big Lebowski","metascore":"69"},
{"Title":"U2 3D","metascore":"83"},
{"Title":"Killing Them Softly","metascore":"64"},
{"Title":"Highlander: Endgame","metascore":"21"},
{"Title":"Knockaround Guys","metascore":"30"},
{"Title":"Freddy Got Fingered","metascore":"13"},
{"Title":"New York Stories","metascore":"N/A"},
{"Title":"Firestarter","metascore":"N/A"},
{"Title":"Barney's Great Adventure","metascore":"N/A"},
{"Title":"The Pirates Who Don't Do Anything: A VeggieTales Movie","metascore":"49"},
{"Title":"Black Snake Moan","metascore":"52"},
{"Title":"De-Lovely","metascore":"53"},
{"Title":"The Love Letter","metascore":"N/A"},
{"Title":"Confidence","metascore":"59"},
{"Title":"Idlewild","metascore":"55"},
{"Title":"The Muse","metascore":"56"},
{"Title":"Here on Earth","metascore":"N/A"},
{"Title":"Raise Your Voice","metascore":"33"},
{"Title":"Whip It","metascore":"68"},
{"Title":"One Day","metascore":"48"},
{"Title":"The Dark Half","metascore":"N/A"},
{"Title":"The Importance of Being Earnest","metascore":"60"},
{"Title":"Peeples","metascore":"52"},
{"Title":"A Mighty Heart","metascore":"74"},
{"Title":"Home Fries","metascore":"45"},
{"Title":"Mulholland Drive","metascore":"81"},
{"Title":"Brainstorm","metascore":"N/A"},
{"Title":"The Rocker","metascore":"53"},
{"Title":"Dark Blue","metascore":"57"},
{"Title":"Boat Trip","metascore":"18"},
{"Title":"Post Grad","metascore":"35"},
{"Title":"The In Crowd","metascore":"14"},
{"Title":"Whatever It Takes","metascore":"20"},
{"Title":"Hoot","metascore":"46"},
{"Title":"Brazil","metascore":"88"},
{"Title":"Whatever Works","metascore":"45"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Kiss Kiss Bang Bang","metascore":"72"},
{"Title":"In Bruges","metascore":"67"},
{"Title":"Idle Hands","metascore":"31"},
{"Title":"Jakob the Liar","metascore":"40"},
{"Title":"Promised Land","metascore":"55"},
{"Title":"Shen zun zhi hu - jing shi tao se jie","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Clan of the Cave Bear","metascore":"N/A"},
{"Title":"Blood and Chocolate","metascore":"33"},
{"Title":"Never Let Me Go","metascore":"69"},
{"Title":"Metropolis","metascore":"98"},
{"Title":"Felicia's Journey","metascore":"72"},
{"Title":"Transsiberian","metascore":"72"},
{"Title":"You Will Meet a Tall Dark Stranger","metascore":"51"},
{"Title":"The Midnight Meat Train","metascore":"58"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Crazy in Alabama","metascore":"46"},
{"Title":"Centurion","metascore":"62"},
{"Title":"The Company","metascore":"73"},
{"Title":"Buffalo Soldiers","metascore":"56"},
{"Title":"Ong-bak 2","metascore":"47"},
{"Title":"Things to Do in Denver When You're Dead","metascore":"46"},
{"Title":"Silent Trigger","metascore":"N/A"},
{"Title":"The Good Night","metascore":"49"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Pandaemonium","metascore":"60"},
{"Title":"Bus 657","metascore":"N/A"},
{"Title":"Automata","metascore":"37"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Return","metascore":"82"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Winnie Mandela","metascore":"37"},
{"Title":"Bathory","metascore":"N/A"},
{"Title":"Groundhog Day","metascore":"72"},
{"Title":"Dungeons & Dragons","metascore":"14"},
{"Title":"Pretty Woman","metascore":"51"},
{"Title":"Manderlay","metascore":"46"},
{"Title":"Unforgiven","metascore":"82"},
{"Title":"Shinjuku Incident","metascore":"63"},
{"Title":"The Towering Inferno","metascore":"N/A"},
{"Title":"Romeo Juliet","metascore":"N/A"},
{"Title":"Slumdog Millionaire","metascore":"86"},
{"Title":"Magic Mike XXL","metascore":"N/A"},
{"Title":"My Bloody Valentine","metascore":"51"},
{"Title":"Cool Runnings","metascore":"N/A"},
{"Title":"Khumba","metascore":"40"},
{"Title":"The Son of No One","metascore":"N/A"},
{"Title":"Born on the Fourth of July","metascore":"75"},
{"Title":"Fatal Attraction","metascore":"67"},
{"Title":"Stomp the Yard","metascore":"44"},
{"Title":"First Blood","metascore":"62"},
{"Title":"All the Queen's Men","metascore":"19"},
{"Title":"Dying of the Light","metascore":"31"},
{"Title":"The Spy Who Loved Me","metascore":"N/A"},
{"Title":"White Fang","metascore":"N/A"},
{"Title":"Poetic Justice","metascore":"51"},
{"Title":"Exorcist II: The Heretic","metascore":"N/A"},
{"Title":"Dangerous Liaisons","metascore":"74"},
{"Title":"Superstar","metascore":"N/A"},
{"Title":"All About the Benjamins","metascore":"34"},
{"Title":"Our Family Wedding","metascore":"38"},
{"Title":"Urban Legend","metascore":"35"},
{"Title":"Tyler Perry's Good Deeds: Creating 'Good' Chemistry","metascore":"N/A"},
{"Title":"Vampire in Brooklyn","metascore":"27"},
{"Title":"A Perfect Getaway","metascore":"63"},
{"Title":"Thinner","metascore":"N/A"},
{"Title":"Jason X","metascore":"25"},
{"Title":"The Iron Lady","metascore":"54"},
{"Title":"An American Haunting","metascore":"38"},
{"Title":"Tea with Mussolini","metascore":"53"},
{"Title":"My Boss's Daughter","metascore":"N/A"},
{"Title":"Jonah: A VeggieTales Movie","metascore":"58"},
{"Title":"Dead Man on Campus","metascore":"27"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Fun Size","metascore":"37"},
{"Title":"New York, New York","metascore":"N/A"},
{"Title":"Hot Tub Time Machine 2","metascore":"29"},
{"Title":"Head Over Heels","metascore":"27"},
{"Title":"Margaret","metascore":"N/A"},
{"Title":"A Walk on the Moon","metascore":"N/A"},
{"Title":"The Lucky Ones","metascore":"N/A"},
{"Title":"Little Children","metascore":"75"},
{"Title":"I Think I Love My Wife","metascore":"49"},
{"Title":"Gossip","metascore":"31"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Crooklyn","metascore":"65"},
{"Title":"Bobby","metascore":"54"},
{"Title":"Flipped","metascore":"45"},
{"Title":"Caravans","metascore":"N/A"},
{"Title":"Soul Survivors","metascore":"20"},
{"Title":"Clueless","metascore":"68"},
{"Title":"Brokeback Mountain","metascore":"87"},
{"Title":"Easy Virtue","metascore":"58"},
{"Title":"Catch a Fire","metascore":"62"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Downfall","metascore":"82"},
{"Title":"Quills","metascore":"70"},
{"Title":"Jefferson in Paris","metascore":"45"},
{"Title":"Teenage Mutant Ninja Turtles","metascore":"31"},
{"Title":"The Ten Commandments","metascore":"N/A"},
{"Title":"No Good Deed","metascore":"26"},
{"Title":"Under the Skin","metascore":"78"},
{"Title":"Black Swan","metascore":"79"},
{"Title":"Seven Psychopaths","metascore":"66"},
{"Title":"The Border","metascore":"N/A"},
{"Title":"Far from Heaven","metascore":"84"},
{"Title":"The Caveman's Valentine","metascore":"44"},
{"Title":"Amen","metascore":"N/A"},
{"Title":"The Last Godfather","metascore":"N/A"},
{"Title":"The Godfather: Part II","metascore":"80"},
{"Title":"Mar adentro","metascore":"N/A"},
{"Title":"Justin Bieber: Never Say Never","metascore":"52"},
{"Title":"Save the Last Dance","metascore":"53"},
{"Title":"Snow Day","metascore":"34"},
{"Title":"Good Morning, Vietnam","metascore":"N/A"},
{"Title":"Earth to Echo","metascore":"53"},
{"Title":"About Last Night","metascore":"62"},
{"Title":"Young Guns","metascore":"50"},
{"Title":"The Butterfly Effect","metascore":"30"},
{"Title":"St. Vincent","metascore":"64"},
{"Title":"This Christmas","metascore":"63"},
{"Title":"Loaded Weapon 1","metascore":"N/A"},
{"Title":"RoboCop","metascore":"67"},
{"Title":"Taps","metascore":"N/A"},
{"Title":"Lost and Found","metascore":"N/A"},
{"Title":"Dick","metascore":"65"},
{"Title":"Admission","metascore":"48"},
{"Title":"Ex Machina","metascore":"78"},
{"Title":"Harriet the Spy","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"A Nightmare on Elm Street 4: The Dream Master","metascore":"N/A"},
{"Title":"Bubble Boy","metascore":"41"},
{"Title":"Child's Play 2","metascore":"N/A"},
{"Title":"Woo","metascore":"N/A"},
{"Title":"The Big Hit","metascore":"31"},
{"Title":"Dude, Where's My Car?","metascore":"30"},
{"Title":"Serial Mom","metascore":"N/A"},
{"Title":"The New Guy","metascore":"24"},
{"Title":"Light It Up","metascore":"43"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Baby Geniuses","metascore":"6"},
{"Title":"The Astronaut Farmer","metascore":"55"},
{"Title":"The Mist","metascore":"58"},
{"Title":"The Perks of Being a Wallflower","metascore":"67"},
{"Title":"Birthday Girl","metascore":"51"},
{"Title":"Crazy/Beautiful","metascore":"61"},
{"Title":"Two Can Play That Game","metascore":"35"},
{"Title":"Letters from Iwo Jima","metascore":"89"},
{"Title":"54","metascore":"33"},
{"Title":"Dirty Work","metascore":"N/A"},
{"Title":"Being John Malkovich","metascore":"90"},
{"Title":"Paris, je t'aime","metascore":"66"},
{"Title":"Resurrecting the Champ","metascore":"55"},
{"Title":"Chloe","metascore":"48"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Find Me Guilty","metascore":"65"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Excessive Force","metascore":"N/A"},
{"Title":"Infamous","metascore":"68"},
{"Title":"The Vatican Tapes","metascore":"N/A"},
{"Title":"The Claim","metascore":"62"},
{"Title":"The Crocodile Hunter: Collision Course","metascore":"50"},
{"Title":"The Emperor's Club","metascore":"N/A"},
{"Title":"Antwone Fisher","metascore":"N/A"},
{"Title":"La guerre du feu","metascore":"N/A"},
{"Title":"Sorority Row","metascore":"N/A"},
{"Title":"The Killer Inside Me","metascore":"53"},
{"Title":"I Love You Phillip Morris","metascore":"65"},
{"Title":"The Call","metascore":"51"},
{"Title":"Attack the Block","metascore":"75"},
{"Title":"Glengarry Glen Ross","metascore":"80"},
{"Title":"The Boy in the Striped Pajamas","metascore":"55"},
{"Title":"Lars and the Real Girl","metascore":"70"},
{"Title":"Womb","metascore":"48"},
{"Title":"Machete","metascore":"60"},
{"Title":"True Romance","metascore":"57"},
{"Title":"The Prisoner of Zenda","metascore":"N/A"},
{"Title":"Conviction","metascore":"61"},
{"Title":"Oscar and Lucinda","metascore":"66"},
{"Title":"Cat People","metascore":"N/A"},
{"Title":"Dancer in the Dark","metascore":"61"},
{"Title":"Think Like a Man","metascore":"51"},
{"Title":"The Perfect Game","metascore":"42"},
{"Title":"The Land Before Time","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Golden Child","metascore":"N/A"},
{"Title":"The Fault in Our Stars","metascore":"69"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Black November","metascore":"31"},
{"Title":"Heaven Is for Real","metascore":"47"},
{"Title":"Casino Jack","metascore":"N/A"},
{"Title":"Girl with a Pearl Earring","metascore":"72"},
{"Title":"American Pie","metascore":"58"},
{"Title":"Frida","metascore":"61"},
{"Title":"Beavis and Butt-Head Do America","metascore":"64"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Prophecy","metascore":"N/A"},
{"Title":"Rachel Getting Married","metascore":"82"},
{"Title":"Act of Valor","metascore":"40"},
{"Title":"War Games","metascore":"N/A"},
{"Title":"Fortress","metascore":"N/A"},
{"Title":"Celebrity","metascore":"41"},
{"Title":"Screwed","metascore":"7"},
{"Title":"From Justin to Kelly","metascore":"14"},
{"Title":"Invaders from Mars","metascore":"N/A"},
{"Title":"Running with Scissors","metascore":"52"},
{"Title":"For Greater Glory: The True Story of Cristiada","metascore":"35"},
{"Title":"The Pursuit of D.B. Cooper","metascore":"N/A"},
{"Title":"Girl 6","metascore":"44"},
{"Title":"Last Orders","metascore":"78"},
{"Title":"Darling Companion","metascore":"41"},
{"Title":"In the Cut","metascore":"46"},
{"Title":"For Your Consideration","metascore":"68"},
{"Title":"2046","metascore":"N/A"},
{"Title":"Gwoemul","metascore":"N/A"},
{"Title":"Charlie Bartlett","metascore":"54"},
{"Title":"Two Lovers","metascore":"74"},
{"Title":"Duma","metascore":"82"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Company Man","metascore":"18"},
{"Title":"Breakfast of Champions","metascore":"42"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Diamonds","metascore":"33"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Triangle","metascore":"N/A"},
{"Title":"Ravenous","metascore":"46"},
{"Title":"Drive Hard","metascore":"29"},
{"Title":"Trade","metascore":"42"},
{"Title":"Gremlins","metascore":"N/A"},
{"Title":"5 Days of War","metascore":"31"},
{"Title":"Married Life","metascore":"65"},
{"Title":"Jackass Number Two","metascore":"66"},
{"Title":"Pet Sematary","metascore":"N/A"},
{"Title":"Madadayo","metascore":"76"},
{"Title":"Brother","metascore":"47"},
{"Title":"St. Trinian's","metascore":"39"},
{"Title":"If I Stay","metascore":"46"},
{"Title":"High School Musical 3: Senior Year","metascore":"57"},
{"Title":"Fateless","metascore":"87"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Frailty","metascore":"64"},
{"Title":"The Perez Family","metascore":"N/A"},
{"Title":"The Dangerous Lives of Altar Boys","metascore":"69"},
{"Title":"The Secret Life of Bees","metascore":"57"},
{"Title":"Out Cold","metascore":"22"},
{"Title":"Jindabyne","metascore":"65"},
{"Title":"Return to the Blue Lagoon","metascore":"N/A"},
{"Title":"Good Will Hunting","metascore":"70"},
{"Title":"Dead Man Walking","metascore":"80"},
{"Title":"The Ladies Man","metascore":"22"},
{"Title":"Army of Darkness","metascore":"57"},
{"Title":"What's Eating Gilbert Grape","metascore":"N/A"},
{"Title":"Quartet","metascore":"64"},
{"Title":"Slackers","metascore":"12"},
{"Title":"Vera Drake","metascore":"83"},
{"Title":"Kinsey","metascore":"79"},
{"Title":"Saw VI","metascore":"30"},
{"Title":"Tomcats","metascore":"15"},
{"Title":"Othello","metascore":"N/A"},
{"Title":"Saw V","metascore":"20"},
{"Title":"Copying Beethoven","metascore":"N/A"},
{"Title":"Inside Llewyn Davis","metascore":"92"},
{"Title":"The Molly Maguires","metascore":"N/A"},
{"Title":"Barry Lyndon","metascore":"N/A"},
{"Title":"The Gospel of John","metascore":"N/A"},
{"Title":"LOL","metascore":"N/A"},
{"Title":"September Dawn","metascore":"25"},
{"Title":"Raising Cain","metascore":"N/A"},
{"Title":"F.I.S.T.","metascore":"N/A"},
{"Title":"The Guru","metascore":"47"},
{"Title":"Corky Romano","metascore":"20"},
{"Title":"Ondine","metascore":"65"},
{"Title":"My Cousin Vinny","metascore":"N/A"},
{"Title":"The Fighter","metascore":"79"},
{"Title":"Kabhi Alvida Naa Kehna","metascore":"N/A"},
{"Title":"Critical Care","metascore":"N/A"},
{"Title":"Doctor Zhivago","metascore":"N/A"},
{"Title":"The Life Before Her Eyes","metascore":"38"},
{"Title":"Housefull","metascore":"N/A"},
{"Title":"Darkness","metascore":"15"},
{"Title":"Lovesick","metascore":"28"},
{"Title":"2001: A Space Odyssey","metascore":"86"},
{"Title":"The Cry of the Owl","metascore":"N/A"},
{"Title":"There Goes My Baby","metascore":"N/A"},
{"Title":"The Grudge","metascore":"49"},
{"Title":"Cruel Intentions","metascore":"56"},
{"Title":"The Last Days on Mars","metascore":"46"},
{"Title":"Brighton Rock","metascore":"N/A"},
{"Title":"Saw III","metascore":"48"},
{"Title":"White Noise","metascore":"30"},
{"Title":"Bill","metascore":"N/A"},
{"Title":"Jeepers Creepers","metascore":"49"},
{"Title":"Insidious: Chapter 3","metascore":"52"},
{"Title":"Stripes","metascore":"N/A"},
{"Title":"The Mighty Ducks","metascore":"N/A"},
{"Title":"The Best Exotic Marigold Hotel","metascore":"62"},
{"Title":"Breakin' All the Rules","metascore":"46"},
{"Title":"Igby Goes Down","metascore":"72"},
{"Title":"Henry V","metascore":"83"},
{"Title":"Chasing Papi","metascore":"33"},
{"Title":"Hamlet 2","metascore":"54"},
{"Title":"The Ice Pirates","metascore":"N/A"},
{"Title":"Undiscovered","metascore":"29"},
{"Title":"PCU","metascore":"N/A"},
{"Title":"Gracie","metascore":"52"},
{"Title":"Glee: The 3D Concert Movie","metascore":"48"},
{"Title":"Princess Kaiulani","metascore":"41"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"The Legend of Suriyothai","metascore":"58"},
{"Title":"The Savages","metascore":"85"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Trust the Man","metascore":"43"},
{"Title":"Velvet Goldmine","metascore":"65"},
{"Title":"The Way of the Gun","metascore":"49"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"All or Nothing","metascore":"72"},
{"Title":"Barbarella","metascore":"N/A"},
{"Title":"The Ultimate Gift","metascore":"49"},
{"Title":"Beautiful","metascore":"23"},
{"Title":"The I Inside","metascore":"N/A"},
{"Title":"Veronika Decides to Die","metascore":"N/A"},
{"Title":"Nightcrawler","metascore":"76"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Leaves of Grass","metascore":"58"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Skin Trade","metascore":"39"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Polisse","metascore":"N/A"},
{"Title":"Beneath Hill 60","metascore":"N/A"},
{"Title":"All Is Lost","metascore":"87"},
{"Title":"Limbo","metascore":"N/A"},
{"Title":"The Rose","metascore":"N/A"},
{"Title":"Quo Vadis?","metascore":"N/A"},
{"Title":"The Wind That Shakes the Barley","metascore":"82"},
{"Title":"Crazy Heart","metascore":"83"},
{"Title":"Crocodile Dundee","metascore":"N/A"},
{"Title":"Namastey London","metascore":"N/A"},
{"Title":"The Namesake","metascore":"N/A"},
{"Title":"Ultramarines: A Warhammer 40,000 Movie","metascore":"N/A"},
{"Title":"Star Wars: The Clone Wars","metascore":"35"},
{"Title":"Election","metascore":"83"},
{"Title":"The Lost Boys","metascore":"63"},
{"Title":"Glitter","metascore":"14"},
{"Title":"Silmido","metascore":"N/A"},
{"Title":"Awake","metascore":"33"},
{"Title":"The City of Your Final Destination","metascore":"52"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Stand by Me","metascore":"N/A"},
{"Title":"The Karate Kid","metascore":"N/A"},
{"Title":"Bright Star","metascore":"81"},
{"Title":"Pulp Fiction","metascore":"94"},
{"Title":"Baggage Claim","metascore":"34"},
{"Title":"The Sound of Music","metascore":"N/A"},
{"Title":"The Inkwell","metascore":"N/A"},
{"Title":"Club Dread","metascore":"45"},
{"Title":"Footloose","metascore":"N/A"},
{"Title":"The Muppet Movie","metascore":"69"},
{"Title":"Akira","metascore":"76"},
{"Title":"Down in the Valley","metascore":"65"},
{"Title":"Swelter","metascore":"N/A"},
{"Title":"Woman on Top","metascore":"41"},
{"Title":"My Name Is Khan","metascore":"50"},
{"Title":"The Singing Detective","metascore":"N/A"},
{"Title":"A Thin Line Between Love and Hate","metascore":"N/A"},
{"Title":"Begin Again","metascore":"62"},
{"Title":"Anomalisa","metascore":"N/A"},
{"Title":"Rabbit-Proof Fence","metascore":"80"},
{"Title":"Nikita","metascore":"N/A"},
{"Title":"Redbelt","metascore":"69"},
{"Title":"Who's Your Caddy?","metascore":"18"},
{"Title":"Dark Angel","metascore":"N/A"},
{"Title":"Auto Focus","metascore":"66"},
{"Title":"The Other Side of Heaven","metascore":"38"},
{"Title":"Split Second","metascore":"N/A"},
{"Title":"I Hope They Serve Beer in Hell","metascore":"26"},
{"Title":"A Dog of Flanders","metascore":"38"},
{"Title":"The Mighty Macs","metascore":"49"},
{"Title":"Somewhere","metascore":"67"},
{"Title":"March or Die","metascore":"N/A"},
{"Title":"Veer-Zaara","metascore":"67"},
{"Title":"The Extra Man","metascore":"N/A"},
{"Title":"We Need to Talk About Kevin","metascore":"68"},
{"Title":"Losin' It","metascore":"51"},
{"Title":"Trudno byt bogom","metascore":"87"},
{"Title":"Hesher","metascore":"45"},
{"Title":"Chairman of the Board","metascore":"N/A"},
{"Title":"Mother and Child","metascore":"64"},
{"Title":"Gerry","metascore":"54"},
{"Title":"High School Musical 2","metascore":"N/A"},
{"Title":"The Terminator","metascore":"84"},
{"Title":"The Heart of Me","metascore":"53"},
{"Title":"Twixt","metascore":"40"},
{"Title":"Stargate: The Ark of Truth","metascore":"N/A"},
{"Title":"The Boondock Saints","metascore":"44"},
{"Title":"Ca$h","metascore":"N/A"},
{"Title":"Paranormal Activity: The Marked Ones","metascore":"42"},
{"Title":"Freddy's Dead: The Final Nightmare","metascore":"N/A"},
{"Title":"Monster","metascore":"74"},
{"Title":"The Elephant Man","metascore":"N/A"},
{"Title":"20,000 Leagues Under the Sea","metascore":"N/A"},
{"Title":"Oculus","metascore":"61"},
{"Title":"Dallas Buyers Club","metascore":"84"},
{"Title":"Memento","metascore":"80"},
{"Title":"Clerks II","metascore":"65"},
{"Title":"Our Idiot Brother","metascore":"60"},
{"Title":"Doug's 1st Movie","metascore":"N/A"},
{"Title":"The Apostle","metascore":"83"},
{"Title":"The Way Way Back","metascore":"68"},
{"Title":"Billy Elliot","metascore":"N/A"},
{"Title":"Mommie Dearest","metascore":"N/A"},
{"Title":"Talk Radio","metascore":"N/A"},
{"Title":"Psycho Beach Party","metascore":"42"},
{"Title":"Joe","metascore":"74"},
{"Title":"Waiting for Guffman","metascore":"71"},
{"Title":"Holy Motors","metascore":"N/A"},
{"Title":"Samsara","metascore":"65"},
{"Title":"Love Stinks","metascore":"23"},
{"Title":"You Kill Me","metascore":"64"},
{"Title":"Poolhall Junkies","metascore":"36"},
{"Title":"Shooting Fish","metascore":"47"},
{"Title":"Mirrormask","metascore":"55"},
{"Title":"The Barbarians","metascore":"N/A"},
{"Title":"Red State","metascore":"50"},
{"Title":"Adoration","metascore":"64"},
{"Title":"The Loss of Sexual Innocence","metascore":"42"},
{"Title":"Mondays in the Sun","metascore":"64"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"An Everlasting Piece","metascore":"56"},
{"Title":"Among Giants","metascore":"N/A"},
{"Title":"Inescapable","metascore":"37"},
{"Title":"Sonny","metascore":"31"},
{"Title":"Trust","metascore":"60"},
{"Title":"The Big Tease","metascore":"53"},
{"Title":"Hell's Angels","metascore":"N/A"},
{"Title":"Prison","metascore":"N/A"},
{"Title":"Stake Land","metascore":"66"},
{"Title":"Thumbsucker","metascore":"69"},
{"Title":"Ben-Hur","metascore":"N/A"},
{"Title":"The Real Cancun","metascore":"34"},
{"Title":"The Perfect Wave","metascore":"N/A"},
{"Title":"Another Happy Day","metascore":"46"},
{"Title":"Four Lions","metascore":"68"},
{"Title":"The Helpers","metascore":"N/A"},
{"Title":"The Art of Getting By","metascore":"36"},
{"Title":"Annie Get Your Gun","metascore":"77"},
{"Title":"The Loved Ones","metascore":"N/A"},
{"Title":"1776","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Alice in Wonderland","metascore":"53"},
{"Title":"The Deported","metascore":"N/A"},
{"Title":"Chicago Overcoat","metascore":"N/A"},
{"Title":"Open Road","metascore":"N/A"},
{"Title":"High Tension","metascore":"42"},
{"Title":"Something Wicked","metascore":"N/A"},
{"Title":"Enter the Dangerous Mind","metascore":"22"},
{"Title":"Amnesiac","metascore":"N/A"},
{"Title":"Northfork","metascore":"64"},
{"Title":"Nowhere Boy","metascore":"67"},
{"Title":"ABCD (Any Body Can Dance)","metascore":"N/A"},
{"Title":"Stranded","metascore":"27"},
{"Title":"Brotherly Love","metascore":"N/A"},
{"Title":"Submarine","metascore":"76"},
{"Title":"Man on Wire","metascore":"89"},
{"Title":"Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb","metascore":"96"},
{"Title":"A Nightmare on Elm Street","metascore":"78"},
{"Title":"Chacun sa nuit","metascore":"N/A"},
{"Title":"The Square","metascore":"84"},
{"Title":"Battle for the Planet of the Apes","metascore":"N/A"},
{"Title":"Hang 'Em High","metascore":"N/A"},
{"Title":"Songcatcher","metascore":"63"},
{"Title":"Sublime","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Beasts of the Southern Wild","metascore":"86"},
{"Title":"A Streetcar Named Desire","metascore":"N/A"},
{"Title":"Deadline","metascore":"N/A"},
{"Title":"Obvious Child","metascore":"76"},
{"Title":"Martha Marcy May Marlene","metascore":"76"},
{"Title":"Who Killed the Electric Car?","metascore":"70"},
{"Title":"Bubba Ho-Tep","metascore":"57"},
{"Title":"Frozen River","metascore":"82"},
{"Title":"Brigham City","metascore":"62"},
{"Title":"No Man's Land","metascore":"84"},
{"Title":"The Act of Killing","metascore":"89"},
{"Title":"Ajami","metascore":"82"},
{"Title":"Junebug","metascore":"80"},
{"Title":"The Battle of Shaker Heights","metascore":"33"},
{"Title":"Wristcutters: A Love Story","metascore":"62"},
{"Title":"The Sidewalks of New York","metascore":"N/A"},
{"Title":"Blue Car","metascore":"76"},
{"Title":"Dream with the Fishes","metascore":"N/A"},
{"Title":"The Future","metascore":"67"},
{"Title":"Walking and Talking","metascore":"67"},
{"Title":"The House of the Devil","metascore":"73"},
{"Title":"Two Girls and a Guy","metascore":"66"},
{"Title":"Slam","metascore":"N/A"},
{"Title":"All the Real Girls","metascore":"71"},
{"Title":"Orgazmo","metascore":"48"},
{"Title":"Lisa Picard Is Famous","metascore":"57"},
{"Title":"The Broken Hearts Club: A Romantic Comedy","metascore":"51"},
{"Title":"Roadside","metascore":"N/A"},
{"Title":"Love in the Time of Monsters","metascore":"N/A"},
{"Title":"Bucky and the Squirrels","metascore":"N/A"},
{"Title":"Crossroads","metascore":"27"},
{"Title":"The Devil's Carnival: Alleluia!","metascore":"N/A"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Paranormal Activity","metascore":"68"},
{"Title":"Subconscious","metascore":"N/A"},
{"Title":"The Toxic Avenger","metascore":"N/A"},
{"Title":"Brick","metascore":"72"},
{"Title":"Going Under","metascore":"N/A"},
{"Title":"Conversations with Other Women","metascore":"62"},
{"Title":"Fight to the Finish","metascore":"N/A"},
{"Title":"Sunday","metascore":"N/A"},
{"Title":"Straight Out of Brooklyn","metascore":"N/A"},
{"Title":"42nd Street","metascore":"N/A"},
{"Title":"Rise of the Entrepreneur: The Search for a Better Way","metascore":"N/A"},
{"Title":"As It Is in Heaven","metascore":"N/A"},
{"Title":"Gory Gory Hallelujah","metascore":"N/A"},
{"Title":"Metropolitan","metascore":"N/A"},
{"Title":"Napoleon Dynamite","metascore":"N/A"},
{"Title":"Fabled","metascore":"N/A"},
{"Title":"Poultrygeist: Night of the Chicken Dead","metascore":"N/A"},
{"Title":"Home Movies","metascore":"N/A"},
{"Title":"My Beautiful Laundrette","metascore":"N/A"},
{"Title":"Jackpot","metascore":"43"},
{"Title":"Trekkies","metascore":"64"},
{"Title":"Maniac","metascore":"47"},
{"Title":"American Ninja 2: The Confrontation","metascore":"N/A"},
{"Title":"The Dark Hours","metascore":"63"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Pancakes","metascore":"N/A"},
{"Title":"Dogtooth","metascore":"N/A"},
{"Title":"My Dog Tulip","metascore":"80"},
{"Title":"undefined","metascore":"undefined"},
{"Title":"Intolerance","metascore":"N/A"},
{"Title":"MTV Movie Special: Tupac Resurrection","metascore":"N/A"},
{"Title":"12 Angry Men","metascore":"N/A"},
{"Title":"God's Army","metascore":"38"},
{"Title":"Compliance","metascore":"68"},
{"Title":"51 Birch Street","metascore":"77"},
{"Title":"The Broadway Melody","metascore":"N/A"},
{"Title":"Halloween","metascore":"85"},
{"Title":"It Happened One Night","metascore":"N/A"},
{"Title":"Let's Talk About Sex","metascore":"N/A"},
{"Title":"Royal Kill","metascore":"N/A"},
{"Title":"Graduation Day","metascore":"N/A"},
{"Title":"Death Calls","metascore":"N/A"},
{"Title":"Better Luck Tomorrow","metascore":"67"},
{"Title":"When the Cat's Away","metascore":"N/A"},
{"Title":"Fighting Tommy Riley","metascore":"53"},
{"Title":"Death Race 2000","metascore":"N/A"},
{"Title":"Old Joy","metascore":"84"},
{"Title":"Revolution","metascore":"N/A"},
{"Title":"Mutual Friends","metascore":"N/A"},
{"Title":"Some Guy Who Kills People","metascore":"N/A"},
{"Title":"Walking to Paris","metascore":"N/A"},
{"Title":"Like Crazy","metascore":"71"},
{"Title":"undefined","metascore":"undefined"}]
};